src/installer/lombok/installer/InstallerGUI.java
When installer window is opened, it would be much better if it would be in a correct location specified by OS instead being at most top left.
=> Minor, put installer window on correct location

AUTHORS, src/core/lombok/ConfigurationKeys.java, src/core/lombok/experimental/UtilityClass.java, src/core/lombok/javac/handlers/HandleUtilityClass.java
Hello! I'd like to say first that I love your project. It is amazing what it opens up with Java, and serves mainly just to show how powerful and extensible this amazing language is.  
This is a feature I am missing very much in the pack for a while now. When we make Utility Classes, i.e., classes only with static methods, we should define a private default constructor, to override the public one that is created if none is presented, and avoid misuse of the class. The best practices would even ask for it to throw and exception when called, to avoid it being used internally or via reflection.  
This class level annotation creates that for you, checks if no other constructors are defined, and also makes all fields, methods and inner classes static, as well as marking the class final for …
=> Adding annotation for creating Utility Classes easily

AUTHORS, src/launch/lombok/launch/ShadowClassLoader.java
Bugfix for missing Jar contents mitigation & 33x performance improvement.
See: https://groups.google.com/forum/#!topic/project-lombok/YNcYxVPM8as
=> Refactor getJarMemberSet(...) & getResourceFromLocation(...)

buildScripts/eclipse-run-tests.template
that also out-of-the-box can run the ecj tests
=> Modify createEclipseLaunchForTestEnvironment to generate a launch file

AUTHORS, src/core/lombok/Value.java
Current `@Value` java doc incorrectly refers to @RequiredArgsConstructor. This was quite misleading for me when viewing the java doc on the fly within the IDE.
=> Updated @Value Java doc to @AllArgsConstructor 

AUTHORS, src/core/lombok/core/GuavaTypeMap.java, src/core/lombok/eclipse/handlers/singulars/EclipseGuavaSetListSingularizer.java, src/core/lombok/eclipse/handlers/singulars/EclipseGuavaSingularizer.java, src/core/lombok/javac/handlers/singulars/JavacGuavaSetListSingularizer.java, src/core/lombok/javac/handlers/singulars/JavacGuavaSingularizer.java, test/transform/resource/after-delombok/BuilderSingularGuavaListsSets.java, test/transform/resource/after-ecj/BuilderSingularGuavaListsSets.java, test/transform/resource/before/BuilderSingularGuavaListsSets.java, website/features/Builder.html
Pull request will resolve #917
=> Added support for builder singular for Guavas ImmutableTable

src/core/lombok/eclipse/handlers/HandleEqualsAndHashCode.java, src/core/lombok/javac/handlers/HandleEqualsAndHashCode.java
Code was changed to use protected in 4d24542dac058fcd, but the comments were left alone.
(tiny change. Was confused when looking at `createCanEqual` as the comments didn't seem to match what the code was doing. Because they don't.)
Signed-off-by: Ross Allan <ross@nallar.me>
=> Update comments with 'public boolean canEqual' to 'protected boolean canEqual'

AUTHORS, buildScripts/ivy.xml, src/core/lombok/ConfigurationKeys.java, src/core/lombok/eclipse/handlers/HandleLog.java, src/core/lombok/extern/jbosslog/JBossLog.java, src/core/lombok/javac/handlers/HandleLog.java, test/core/src/lombok/RunTestsViaEcj.java, test/transform/resource/after-delombok/LoggerJBossLog.java, test/transform/resource/after-ecj/LoggerJBossLog.java, test/transform/resource/before/LoggerJBossLog.java
This is my first contribution to lombok.
I ran `ant test` and tested the generated lombok dist jar in eclipse which correctly generated the JBoss Logger field.
I manually put the jboss-logging-3.3.0.Final.jar into  /lombok/lib/test/jboss-logging.jar to run the tests since I couldn't find another way to get the jar there - may be I missed something in the build process.
Cheers,
Thomas
=> Added support for JBoss Logging v3.3.0-Final via @JBossLog [Issue #1103]

website/mavenrepo/index.html
Fix: gradle current documentation is partially true (work only if build contain a "war" task)
Fix: new versions of gradle (>= 2.12) should use the new `compileOnly` scope
Gradle documentation is a bit obsolete, here's a quick fix.
Cheers
=> update gradle configuration documentation

src/core/lombok/Value.java
Value is no longer experimental, so (as the person who raised the issue
suggested) the Javadoc should no longer point to the 'experimental'
documentation. Fixes #1091
=> Update Javadoc URL on Value

AUTHORS, website/index.css, website/setup/ecj.html, website/setup/pom.xml
As requested by Roel.
These changes add instructions for how to get lombok to hook into an Eclipse compiler in `maven-compiler-plugin`. We are trying to emulate the Eclipse problem view by parsing the logs from a Maven build that uses the Eclipse compiler in a lombok-enabled project.
=> Update instructions for using lombok with ecj and Maven

AUTHORS, src/core/lombok/core/AnnotationProcessor.java
It fixes `lombok` `1.16` doesn't works in `maven-compiler-plugin` `2.3.2` or old.
http://stackoverflow.com/questions/34358689
Furthermore, `maven-compiler-plugin` `2.4` requires `plexus-compiler-javac` `1.8.6`, which drops `org.codehaus.plexus.compiler.javac.IsolatedClassLoader`.
I love hack, but hate such hard code to fix possible problem.
=> always return ShadowClassLoader.

src/core/lombok/javac/handlers/HandleDelegate.java
ListBuffer<JCExpression> bounds = types.getBounds((TypeVar) param).isEmpty() ? null : new     ListBuffer<JCExpression>();
for (Type type : types.getBounds((TypeVar) param)) {
bounds.append(JavacResolution.typeToJCTree(type, annotation.getAst(), true));
}
--> if bounds is null, npe here
typeParams.append(maker.TypeParameter(name, bounds.toList()));
=> guard against possible npe

AUTHORS, src/eclipseAgent/lombok/eclipse/agent/EclipsePatcher.java, src/eclipseAgent/lombok/launch/PatchFixesHider.java
Patches the bytecode of RenameFieldProcessor and removes all methods marked with @Generated from the search results to avoid eclipse refactoring them.
Fixes Issue #210
=> Patch for renaming fields with Getter/Setter/Data in eclipse #210

AUTHORS, src/core/lombok/javac/apt/LombokFileObjects.java, src/stubs/com/sun/tools/javac/file/BaseFileManager.java
I've created a workaround to fix the issue #1440, #1472 for IntelliJ + Java9.
It works for me with IntelliJ 2017.3 EAP.
The wrappedManager is proxied with java.lang.reflect.Proxy, so it can't be cast to BaseFileManager.
So I created BaseFileManagerWrapper to wrap it.
=> fix issue #1440, #1472: wrap BasedFileManager for jdk9

src/core/lombok/ToString.java
It looks like there was a copy paste error in the javadoc it mentioned equals in the toString docs
=> fix JavaDoc of callSuper in the ToString annotation

usage_examples/ToStringExample_pre.jpage
I think line 12 is incorrect, call `this.getName()` in it self will cause stackoverflow.Change to return `this.name`.
=> getName call it self result in stackoverflow

doc/changelog.markdown
I guess 1.16.18 has improved JDK9 support "since 1.16.16", not "1.16.6"?
=> Update changelog: 1.16.[1]6 typo ?

src/core/lombok/Cleanup.java
I've fixed documentation for Cleanup annotation. Doc provided before wrong variable information (you closed String instead of Closeable).
=> Wrong documentation variables fix.

src/core/lombok/Lombok.java
Currently, the following code triggers a warning in IntelliJ.
(I'm using the current version, 2016.3.4.)
`    throw Lombok.sneakyThrow(e);`
> Dereference of 'Lombok.sneakyThrow(e)' may produce 'java.lang.NullPointerException'.
This change eliminates the warning.
All tests pass. I ran:
ant setupJavaOpenJDK6TestEnvironment
ant test
ant setupJavaOpenJDK7TestEnvironment
ant test
ant setupJavaOracle7TestEnvironment
ant test
ant setupJavaOracle8TestEnvironment
ant test
=> Avoid "possible NPE" warnings for `throw Lombok.sneakyThrow(e)`

src/core/lombok/javac/apt/LombokFileObjects.java
Add a JavaFileManager class name to KNOWN_JAVA9_FILE_MANAGERS,
for IntelliJ build with JDK10.
=> [fix] Fix intellij build with jdk10 (#1572)

src/core/lombok/core/AnnotationValues.java, src/core/lombok/javac/handlers/JavacHandlerUtil.java
I'm writing my custom annotations (and handlers) and need to process an annotation in the form
``` java
@MyAnnotation(
a="a",
attr={
@MyAttribute(name="test"),
@MyAttribute(name="test2")
})
```
This is not possible in lombok 1.16.4, but with this small changes I got it working. I tested it only using lombok 1.16.4 and javac, as I do not use eclipse.
=> implemented support for annotation arrays as annotation attributes in javac

src/installer/lombok/installer/eclipse/EclipseProductLocationProvider.java
change NotAnIdeLocationException to CorruptedIdeLocationException in javadoc for private method create0(String path)
=> fix typo in EclipseProductLocationProvider.java

src/core/lombok/core/configuration/NullCheckExceptionType.java
Currently it is "NullPointerException: someFieldName" and that is not very
telling as to the reasons this exception is thrown. It should be easily identifiable that this is due to a Lombok null check.
=> Make the null check exception a little bit more explicit

src/core/lombok/core/AnnotationProcessor.java, src/core/lombok/javac/apt/LombokProcessor.java
Looks like incremental compilation API has changed in 4.8, causing Lombok init to fail:
```
warning: lombok.javac.apt.LombokProcessor could not be initialized. Lombok will not run during this compilation:
java.lang.ClassCastException: org.gradle.api.internal.tasks.compile.processing.IncrementalFiler cannot be cast to jdk.compiler/com.sun.tools.javac.processing.JavacFiler
```
This change should get Lombok working again on Gradle 4.8 and above; fixes #1716 
CC: @pbi-qfs
=> Fix #1716: Update for Gradle incremental compilation API change in Gradle 4.8 and above

src/core/lombok/bytecode/ClassFileMetaData.java
This PR replaces a StringBuilder by simple char array which adds a little bit of performance
This method was identified as a hotspot method by jprofiler with 214k calls in my test project.
this change improves the run time for 214k calls from 1165ms to 109ms
=> [Performance] Replaced StringBuilder by simple char array in "hotspot" method

website/usageExamples/LogExample_post.jpage, website/usageExamples/LogExample_pre.jpage
I replaced the `error` method invocation in the `@Log` examples with `severe`, because `java.util.logging.Logger` does not have an `error` method (as per https://docs.oracle.com/javase/10/docs/api/java/util/logging/Logger.html)
=> java.util.logging.Logger does not have an error method.

src/core/lombok/core/AST.java, src/core/lombok/core/AnnotationProcessor.java, src/core/lombok/core/LombokInternalAliasing.java, src/core/lombok/eclipse/EclipseASTAdapter.java, src/core/lombok/eclipse/EclipseASTVisitor.java, src/core/lombok/eclipse/EclipseNode.java, src/core/lombok/eclipse/HandlerLibrary.java, src/core/lombok/eclipse/TransformEclipseAST.java, src/eclipseAgent/lombok/launch/PatchFixesHider.java, src/launch/lombok/launch/Agent.java, src/launch/lombok/launch/AnnotationProcessor.java, src/launch/lombok/launch/Main.java, src/launch/lombok/launch/ShadowClassLoader.java, src/utils/lombok/eclipse/Eclipse.java
This PR brings several optimizations for the ECJ, especially when using it in a multi module maven build (as I do) - also the eclipse performance should be better, especially on modules that do not use lombok.
**So: some numbers:**
1. Single maven project, not using lombok ~ 1200 class files:
|Type of build |Total maven build time | Est. compile time| Note |
|--------------|------------------------|------------------|------|
| No lombok   | ~8.5 sec                      |     5.0 sec  | this is the 'reference' build time, as this project can be built without lombok|
| 1.18.0 - original | ~12.5 sec | 9.0 sec | just adding lombok (as eclipse does by default for all projects) will nearly double the compile time, because lombok tries to enhance EVERY class. I tried ti scan for "interesting …
=> Reduced the AST traverse calls to improve ECJ performance

src/core/lombok/eclipse/handlers/HandleBuilder.java
The fix for #1759 in commit 5ec61bb only fixed the flagUsage handling for javac, not Eclipse.
=> [fixes #1759] ‘flag usage’ check on builder for eclipse

src/core/lombok/core/LombokNode.java, src/core/lombok/eclipse/EclipseNode.java, src/core/lombok/javac/JavacNode.java
There are many calls like `ast.traverseChildren` - due type erasue, ast was internally stored as object, which leads to a "checkcast" before each "invokevirtual" in the byte code.
This PR and #1763 reduces the total time spent in the `traverse` method (30M calls) from 52276ms to 51246ms.
=> [Performance] use declared ast Type instead of generic one 

src/core/lombok/eclipse/handlers/HandleSuperBuilder.java, src/core/lombok/javac/handlers/HandleBuilder.java, src/core/lombok/javac/handlers/HandleSuperBuilder.java, test/transform/resource/after-delombok/SuperBuilderWithDefaults.java, test/transform/resource/after-delombok/SuperBuilderWithNonNull.java, test/transform/resource/after-ecj/SuperBuilderWithDefaults.java, test/transform/resource/after-ecj/SuperBuilderWithNonNull.java, test/transform/resource/before/SuperBuilderWithNonNull.java
With this change, `@SuperBuilder` works also for fields that are `final` and `@Builder.Default`. Furthermore, the `@NonNull` code also checks the default value for `!= null`.
This fixes #1800.
This PR includes PR #1818, so you may want to review/merge #1818 first (or just review/merge this one to have it all).
=> SuperBuilder fix for Builder.Default, final, and NonNull fields

src/core/lombok/eclipse/handlers/HandleSuperBuilder.java, src/core/lombok/javac/handlers/HandleSuperBuilder.java, test/transform/resource/after-delombok/SuperBuilderWithGenerics.java, test/transform/resource/after-delombok/SuperBuilderWithGenerics2.java, test/transform/resource/after-ecj/SuperBuilderWithGenerics.java, test/transform/resource/after-ecj/SuperBuilderWithGenerics2.java
The `self()` method in the `@SuperBuilder` implementation class lacked generics on the return type. As the implementation class is private and only the abstract class is visible to users, this did not affect user experience, but resulted in a compiler warning when using the delomboked code.
This fix adds the generics to the methods, avoiding the (typically suppressed) compiler warning.
=> SuperBuilder self() method signature generics fix

jitpack.yml
Subsequent to #1780 
Sample build outcome:
https://jitpack.io/com/github/mmoayyed/lombok/jitpack11-v1.18.0-gcf9f25a-152/build.log
=> Allow jitpack to use JDK 10 when building lombok

website/usageExamples/experimental/UtilityClassExample_post.jpage, website/usageExamples/experimental/UtilityClassExample_pre.jpage
Method in code example (https://projectlombok.org/features/experimental/UtilityClass) has `void` return type instead of `int`.
=> Fix code example for @UtilityClass

doc/utils-maven-pom.xml
Motivation
The published maven POM for lombok refers to Google Code for issue
management (see [here](https://search.maven.org/artifact/org.projectlombok/lombok/1.18.2/pom)). Google code is no longer active.
Changes
- replace with github issues for issue management
=> correct issueManagement declaration in maven POM

src/core/lombok/core/handlers/HandlerUtil.java
This pull request augments Lombok's list of NonNull and copyable annotations.
It adds annotations defined by the [Checker Framework](https://checkerframework.org/).
=> Add Checker Framework NonNull and Nullable annotations

website/templates/features/experimental/SuperBuilder.html
Documentation for `@SuperBuilder(toBuilder = true)` now mentions that it requires `toBuilder` on all superclasses.
=> Documentation improvements for SuperBuilder

src/core/lombok/javac/handlers/HandleBuilder.java, src/core/lombok/javac/handlers/HandleSuperBuilder.java, src/core/lombok/javac/handlers/JavacSingularsRecipes.java, src/core/lombok/javac/handlers/singulars/JavacGuavaSingularizer.java, src/core/lombok/javac/handlers/singulars/JavacJavaUtilListSetSingularizer.java, src/core/lombok/javac/handlers/singulars/JavacJavaUtilListSingularizer.java, src/core/lombok/javac/handlers/singulars/JavacJavaUtilMapSingularizer.java, src/core/lombok/javac/handlers/singulars/JavacJavaUtilSetSingularizer.java, src/core/lombok/javac/handlers/singulars/JavacJavaUtilSingularizer.java
As I was working on #2004, I noticed this part of the code looked like it could need some love. The main changes are
- Split the `generateMethods` methods up into parts so that identical parts can be reused between them.
- Condense the "use Guava instead" logic into a single check which replaces the whole singularizer instance once instead of sprinking `if (useGuavaInstead())` checks all over the place.
When I started, I expected the end result would be more substantial than a net -42 LOC change (-69 if ignoring whitespace), so I was a bit underwhelmed by the reduction volume and I'm not sure it's worth the rather extensive code changes. That said, the changes are organised into small commits such that it's easy to manually verify the correctness of each step, and I do believe that …
=> Reduce code duplication in singularizers

src/delombok/lombok/delombok/ant/DelombokTask.java
Method createFormat() causes ambiguous behavior and shouldn't be used with addFormat(), especially because the created format instance doesn't being added to the formatOptions.
This fixes #1040
=> remove createFormat() method (#1040 fix)

website/templates/main.html
OCI moved their Java News Briefs (JNB) to a more general format called Software Engineering Tech Trends (SETT).  This changed the link for the article featuring Project Lombok.
This minor modification corrects the JNB link to the current location of the article.
=> Updated the text explanation link.

src/core/lombok/javac/handlers/HandleDelegate.java, src/core/lombok/javac/handlers/HandleVal.java, test/transform/resource/after-delombok/ValDelegateMethodReference.java, test/transform/resource/after-ecj/ValDelegateMethodReference.java, test/transform/resource/before/ValDelegateMethodReference.java
The javac's HandleDelegate generates code before the HandleVal.
=> #1976. A handlers' order has been changed.

src/eclipseAgent/lombok/eclipse/agent/PatchVal.java, test/transform/resource/after-delombok/ValInLambda.java, test/transform/resource/after-delombok/ValLambda.java, test/transform/resource/after-ecj/ValInLambda.java, test/transform/resource/after-ecj/ValLambda.java, test/transform/resource/before/ValInLambda.java, test/transform/resource/before/ValLambda.java, test/transform/resource/messages-ecj/ValLambda.java.messages
Sorry for being late. 
I forget to add some code that replaces an error handling policy in EJC in the type resolve method. It is necessary to guarantee that AbortCompilation will be thrown when a type evaluation of then false part being failed in a conditional expression. Implementing the stopOnFirstError method in IErrorHandlingPolicy may return false, which will result in an error message, 
but the compilation will not be interrupted by AbortCompilation throwing.
Example:
```console
LOMBOK=./dist/lombok-1.18.9.jar
ECJ=./lib/ecj8/org.eclipse.jdt.core.compiler-ecj.jar
RT=./lib/oracleJDK8Environment/rt.jar
CLASS_SRC=./test/transform/resource/before/ValLambda.java
java -javaagent:$LOMBOK -jar $ECJ -classpath $RT:$LOMBOK -1.8 $CLASS_SRC
```
there will be errors:
```console
----------
1. …
```
=> val. override error handling policy for problemReporter to guarantee AbortCompilation is throwing.

src/eclipseAgent/lombok/eclipse/agent/EclipsePatcher.java, src/eclipseAgent/lombok/launch/PatchFixesHider.java
When annotations based null analysis is enabled in Eclipse and NonNullByDefault is in effect, @lombok.NonNull causes warning, e.g. in the following example:
```
import org.eclipse.jdt.annotation.NonNullByDefault;
import lombok.NonNull;
@NonNullByDefault
public class App {
String f(@NonNull String s) {
return s;
}
}
```
two warnings are reported  at the `@NonNull` annotation:
- `Dead code`
- `Redundant null check: comparing '@NonNull String' against null`
(obviously, both warnings are only reported when enabled in the Compiler preferences)
=> Avoid Eclipse warnings about lombok.NonNull when NonNullByDefault is used

AUTHORS, doc/changelog.markdown, src/core/lombok/core/configuration/TypeName.java, src/core/lombok/eclipse/handlers/EclipseHandlerUtil.java, src/core/lombok/eclipse/handlers/HandleFieldNameConstants.java, src/core/lombok/eclipse/handlers/HandleLog.java, src/core/lombok/javac/handlers/HandleLog.java, src/core/lombok/javac/handlers/JavacHandlerUtil.java, website/templates/features/log.html
I noticed the style and tried to keep it mostly; I missed some places though. Thanks for fixing them.
I have no complaints to the changes.
There is one improbable breaking change: setting `lombok.log.fieldName=private` used to be valid (and it compiled!); similarly `lombok.fieldNameConstants.innerTypeName=42`, `lombok.copyableAnnotations+=int.float.package.class`, and `lombok.copyableAnnotations+=a-b-c`.
I also found two bugs regarding `TypeName`.
=> Fixes for CustomLog, AUTHORS entry, extended changlog

src/launch/lombok/launch/ShadowClassLoader.java
Lombok extensions in external jar files were not included by class loader. There is a related discussion here https://stackoverflow.com/questions/35550460/writing-custom-lombok-annotation-handlers
=> Fix loading extensions

website/templates/setup/gradle.html
The linked gradle plugin doesn't work with Gradle 2.12 (which is way too old anyway) and doesn't support running the eclipse installer.
=> Update gradle documentation

src/core/lombok/eclipse/handlers/HandleSuperBuilder.java, src/core/lombok/javac/handlers/HandleSuperBuilder.java, test/transform/resource/after-delombok/SuperBuilderNameClashes.java, test/transform/resource/after-ecj/SuperBuilderNameClashes.java, test/transform/resource/before/SuperBuilderNameClashes.java, test/transform/resource/messages-ecj/SuperBuilderNameClashes.java.messages
Previously, the names of the type parameters of `@SuperBuilder` are chosen that they do not collide with the type parameters of the annotated class.
With this PR, the classname of the annotated class and the type names of fields in that class are also considered in this collision check.
This fixes #2297.
=> Avoid more name clashes for SuperBuilder

src/core/lombok/eclipse/handlers/HandleSuperBuilder.java, src/core/lombok/experimental/SuperBuilder.java, src/core/lombok/javac/handlers/HandleSuperBuilder.java, test/transform/resource/after-delombok/SuperBuilderCustomized.java, test/transform/resource/after-delombok/SuperBuilderCustomizedWithSetterPrefix.java, test/transform/resource/after-delombok/SuperBuilderWithSetterPrefix.java, test/transform/resource/after-ecj/SuperBuilderCustomized.java, test/transform/resource/after-ecj/SuperBuilderCustomizedWithSetterPrefix.java, test/transform/resource/after-ecj/SuperBuilderWithSetterPrefix.java, test/transform/resource/before/SuperBuilderCustomized.java, test/transform/resource/before/SuperBuilderCustomizedWithSetterPrefix.java, test/transform/resource/before/SuperBuilderWithSetterPrefix.java
Following the lead of PR #2174, I implemented `setterPrefix` for `@SuperBuilder` too.
=> setter prefixes for SuperBuilder

src/core/lombok/javac/handlers/HandleSuperBuilder.java, test/transform/resource/after-delombok/SuperBuilderNestedGenericTypes.java, test/transform/resource/after-ecj/SuperBuilderNestedGenericTypes.java, test/transform/resource/before/SuperBuilderNestedGenericTypes.java
The javac `@SuperBuilder` implementation now works correctly with nested generic type parameters in the extends clause of the annotated class.
This fixes #2359.
=> SuperBuilder javac fix for nested generic types

src/eclipseAgent/lombok/eclipse/agent/EclipsePatcher.java
Fixes #2375 
The jdt project moved the class to a different folder and renamed it in https://github.com/eclipse/eclipse.jdt.ui/commit/6ece2a50057bbe10757d0a4f5349135646c0b0cc
=> Add moved CodeStyleFix to patch list

AUTHORS, src/eclipseAgent/lombok/eclipse/agent/PatchExtensionMethod.java
This PR fixes #1441, #1695, and #2236. 
As discussed [here](https://groups.google.com/forum/#!topic/project-lombok/qNu0SUGxNjQ) it uses reflection to support older eclipse versions.
=> Set missing argumentTypes for eclipse extension methods

src/launch/lombok/launch/ShadowClassLoader.java
url.toString is not encoded properly, so to not lose the "+" in the url one has to properly encode it before decoding other chars like " " are correctly encoded
According to https://docs.oracle.com/javase/7/docs/api/java/net/URLDecoder.html this behaviour is correct "+" is Encoded as " " which is not the file someone whants
This Fixes #1536
=> Encode partial URL. Fixes #1536

src/eclipseAgent/lombok/eclipse/agent/EclipsePatcher.java, src/eclipseAgent/lombok/launch/PatchFixesHider.java
This on fixes #2286.
You can use this class to reproduce the original issue (delegating a method with vararg array e.g. `String[]...` parameter)
```java
import lombok.experimental.Delegate;
public class A {
@Delegate
private A.B delegate;
public class B {
public void varargs(Object[]... keys) {
}
}
}
```
=> [fixes #2286] Set source range for vararg arrays

src/core/lombok/eclipse/handlers/EclipseHandlerUtil.java, test/transform/resource/after-delombok/TypeUseAnnotations.java, test/transform/resource/after-ecj/TypeUseAnnotations.java, test/transform/resource/before/TypeUseAnnotations.java
This PR fixes #2246.
An annotated generic type (`List<TypeUseAnnotations.@TA(x = 5) Inner>` returns an annotatons array with null values(`[null, [TA]]`). The copy method can now handle these cases.
I also added a simple test.
=> Add null check in copyTypeAnns

src/core/lombok/core/handlers/HandlerUtil.java, src/core/lombok/eclipse/handlers/EclipseHandlerUtil.java, src/core/lombok/eclipse/handlers/singulars/EclipseGuavaSingularizer.java, src/core/lombok/eclipse/handlers/singulars/EclipseJavaUtilListSetSingularizer.java, src/core/lombok/eclipse/handlers/singulars/EclipseJavaUtilMapSingularizer.java, src/core/lombok/javac/handlers/HandleJacksonized.java, src/core/lombok/javac/handlers/JavacHandlerUtil.java, src/core/lombok/javac/handlers/JavacSingularsRecipes.java, test/stubs/com/fasterxml/jackson/annotation/JsonAnySetter.java, test/transform/resource/after-delombok/JacksonBuilderSingular.java, test/transform/resource/after-ecj/JacksonBuilderSingular.java, test/transform/resource/before/JacksonBuilderSingular.java
In #2419, we investigated which further Jackson annotations should be copied: `@JacksonXmlProperty`, `@JsonDeserialize`, `@JsonIgnore`, and `@JacksonInject`; details in the issue discussion. 
(There are probably a few more of those annotation in the JAXB annotation package, but I never worked with those, so I'm not sure for which of these annotations copying would be always correct.)
Furthermore, with this PR, annotations are copied to `@Singular` methods. Most copyable annotations are put on the "regular" plural method, as this is what Jackson expects. The only exception is `@JsonAnySetter`, which is copied to the singular method (it only works on that).
=> Copy more Jackson annotation to the builder, also to @Singular methods

src/core/lombok/eclipse/handlers/HandleFieldNameConstants.java
This PR resolves #1969. The field `enumConstantsCounter` must be set to the field count, otherwise `Enum.values()` returns an incomplete list
=> Enum.values() requires enumConstantsCounter to be set

src/utils/lombok/permit/Permit.java
Currently lombok crashes when building with OpenJ9 JDK as described in #2414 
It is due to the `override` field offset from Fake.class doesn't match actual offset value for AccessibleObject.class in OpenJ9 
This change is to support the OpenJ9 Field layout algorithm.
=> Update Fake.class to support OpenJ9 Field Layout

src/core/lombok/javac/handlers/HandleDelegate.java, test/transform/resource/after-delombok/DelegateGenerics.java, test/transform/resource/after-ecj/DelegateGenerics.java, test/transform/resource/before/DelegateGenerics.java
This PR resolves #2382. 
`supertype_field` and `interfaces_field` are empty if the parent uses generics. The method `types.directSupertypes` returns the parent and sets the generic type information properly.
=> Handle generic supertypes

src/core/lombok/javac/handlers/HandleDelegate.java, src/eclipseAgent/lombok/eclipse/agent/PatchDelegate.java, test/transform/resource/after-delombok/DelegateAlreadyImplemented.java, test/transform/resource/after-ecj/DelegateAlreadyImplemented.java, test/transform/resource/before/DelegateAlreadyImplemented.java
All implemeted method signatures gets added to `banList`. The javac code was already there, I only added the eclipse code.
This PR resolves #2006.
=> [fixes #2006] Delegate now excludes already implemented methods

doc/changelog.markdown, src/core/lombok/javac/handlers/HandleWith.java
This fixes #2463.
Anyone can think of more places this could be of an issue?
=> [Fixes #2463] Clone type to correctly set annotated type on with methods

src/core/lombok/javac/handlers/HandleBuilder.java, test/transform/resource/after-delombok/BuilderConstructorJavadoc.java, test/transform/resource/after-ecj/BuilderConstructorJavadoc.java, test/transform/resource/before/BuilderConstructorJavadoc.java
As discussed in #2481 `@Builder` now copies the `@param` part of the constructor javadoc to the generated builder method.
=> [fixes #2481] Copy constructor javadoc to builder methods

AUTHORS, src/core/lombok/EqualsAndHashCode.java, src/core/lombok/core/handlers/InclusionExclusionUtils.java, test/transform/resource/after-delombok/EqualsAndHashCodeRank.java, test/transform/resource/after-ecj/EqualsAndHashCodeRank.java, test/transform/resource/before/EqualsAndHashCodeRank.java
Given some special cases where we need to explicitly order the comparation fields for performance improvement, I have applied the same idea that we have for `@ToString.Include(rank = -1)`. ie.: `@EqualsAndHashCode.Include(rank = -1)`
Also, there are some discussions related to this here (#1543) about the Equals algorithm and performance. So, given this flexibility can help me with some special cases and I believe that can be helpful for more people too. Let me know what you think folks.
=> [Feature request] @EqualsAndHashCode Flexibility for rank properties for equal/hashcode method

src/core/lombok/eclipse/handlers/HandleUtilityClass.java, src/core/lombok/javac/handlers/HandleUtilityClass.java
The changes introduced in 94440a8bd73f176637a9890dc10df67d26615674 breaks the test case. This PR fixes that.
=> Fix UtilityClass test case

src/core/lombok/eclipse/EclipseAST.java, src/core/lombok/eclipse/handlers/EclipseHandlerUtil.java, src/core/lombok/javac/JavacAST.java
This PR contains 3 commits that address some performance related things I noticed while profiling builds for #2489 .
The first one replaces `Class.getSimpleName()` with `Class.getName()` because the former is slow.
JDK Bug: https://bugs.openjdk.java.net/browse/JDK-8187123
Before:
After:
The second one caches the absoulte file location of the compilation unit. `File.toURI()` requires a disk access and can take some time.
Before:
After:
The last one is trivial and simply removes a NPE
=> Various performance fixes

src/core/lombok/eclipse/handlers/HandleBuilder.java, src/core/lombok/eclipse/handlers/HandleSuperBuilder.java, src/eclipseAgent/lombok/eclipse/agent/PatchDelegate.java, test/transform/resource/after-ecj/CheckerFrameworkSuperBuilder.java, test/transform/resource/after-ecj/SimpleTypeResolution.java, test/transform/resource/messages-ecj/CheckerFrameworkBasic.java.messages, test/transform/resource/messages-ecj/CheckerFrameworkSuperBuilder.java.messages
During profiling I noticed that `PatchDelegate.isDelegate()` consumes some time during compilation. I noticed that the type resolution of the annotation is responsible for that. Even if I'm not sure if that this increases the compilation time I added an additional check that returns early.
This causes some interesting side effects as it broke some unrelated test cases. After checking out why, I think that the unsuccessful type resolution (due to the unknown ckeckerframework annotation) stops compilation to early and hides the underlying problem. It seems like the `this` parameter have to be set as `Receiver` instead of an `Argument` in eclipse. Otherwise it fails with `Only the first formal parameter may be declared explicitly as 'this'`.
I think I fixed that but couldn't test it in a …
=> Skip type resolution in isDelegate

src/core/lombok/javac/JavacTransformer.java
While analyzing heap dumps for #2240 I noticed that lombok keeps some unnecessary objects in memory. This PR changes that.
I also removed some old code that copies a list into a new one which actualy does not change anything. This snippet was part of an old experiment and even contains an if condition that can never be true.
=> Reduce memory usage

src/eclipseAgent/lombok/eclipse/agent/EclipsePatcher.java
This PR fixes #977. 
Unfortunately, as with all these changes, it is not possible to create a test case.
=> Set generated flag for annotation names

src/core/lombok/Builder.java
The javadoc on Builder.java says it generates a private constructor, which is the typo. it need to be updated, because the official document, [here](https://projectlombok.org/features/Builder), says:
> applying @Builder to a class is as if you added @AllArgsConstructor(access = AccessLevel.PACKAGE) to the class.  
we can make sure `@Builder` on the class generates a package-private constructor by running the following Junit test. **see carefully the package declaration**.
```java
package lombok.learning.builder;
import lombok.Builder;
@Builder
public class Student {
private String name;
private Integer height;
}
```
```java
package lombok.learning.builder;
import org.junit.Test;
public class StudentTest {
@Test
public void canAccessToPackagePrivateConstructor() {
Student student = new …
```
=> update javadoc on Builder.java

src/core/lombok/core/PostCompiler.java
In some cases (#2539) writing the class file throws an exception. If that happens the stream is empty if it gets closed. This will lead to an exception that hides the original one.
=> Skip PostCompiler for empty byte arrays

test/core/src/lombok/AbstractRunTests.java, test/transform/resource/after-delombok/GetterSetterJavadoc.java
By chance I noticed that one of the test cases contains an error. During debugging I figured out that the `trimRight` method always removes the last character of the passed string.
=> Compare full line instead of ignoring the last character

src/core/lombok/javac/handlers/JavacHandlerUtil.java, src/stubs/com/sun/tools/javac/code/Symbol.java, src/stubs/com/sun/tools/javac/code/Symtab.java
Second attempt to fix it after https://github.com/rzwitserloot/lombok/pull/2497
I have tested it and parameter names and annotations are correctly propagated now.
Fixed https://github.com/micronaut-projects/micronaut-core/issues/3918
=> Fix missing parameter names, annotations in following annotation processors 2

website/usageExamples/BuilderExample_post.jpage
Hi,
I have noticed a discrepancy in the documentation on the variable type of the `occupation` variable for the Builder documentation. Therefore, I have decided to make a pull request to correct the mistake. Feel free to close this if the change is incorrect.
Thanks!
=> changed arraylist to set in builder doc

src/core/lombok/eclipse/EclipseAugments.java, src/eclipseAgent/lombok/eclipse/agent/EclipsePatcher.java, src/eclipseAgent/lombok/eclipse/agent/PatchDelegate.java, src/eclipseAgent/lombok/eclipse/agent/PatchDelegatePortal.java, src/eclipseAgent/lombok/launch/PatchFixesHider.java
This PR adds the generated delegate methods to the outline view in eclipse.
Eclipse creates an internal representation for the open file (`SourceType`) and displays all the children in the outline view. This PR patches this `getChildren` method to add new `SourceMethod` objects. These method objects gets stored in the compilation unit by the delegate handler. In some cases the delegate handler runs after eclipse calls `getChildren`, thats why the handler now fires an event to trigger an update of the outline view.
I also successfully tested these changes in an old eclipse version.
Fixes #1455
=> Add generated delegate methods to eclipse outline

src/eclipseAgent/lombok/eclipse/agent/EclipsePatcher.java, src/eclipseAgent/lombok/eclipse/agent/PatchExtensionMethod.java, src/eclipseAgent/lombok/launch/PatchFixesHider.java, test/transform/resource/after-delombok/ExtensionMethodSuppress.java, test/transform/resource/after-ecj/ExtensionMethodSuppress.java, test/transform/resource/before/ExtensionMethodSuppress.java, test/transform/resource/messages-ecj/ExtensionMethodSuppress.java.messages
The `@ExtensionMethod` feature to suppress base methods was broken, this PR resolves that.
=> Fix suppressBaseMethods in ecj/eclipse

src/core/lombok/javac/handlers/HandleExtensionMethod.java, src/eclipseAgent/lombok/eclipse/agent/EclipsePatcher.java, src/eclipseAgent/lombok/eclipse/agent/PatchExtensionMethod.java, src/eclipseAgent/lombok/launch/PatchFixesHider.java, test/transform/resource/after-delombok/ExtensionMethodNames.java, test/transform/resource/after-delombok/ExtensionMethodSuppress.java, test/transform/resource/after-ecj/ExtensionMethodNames.java, test/transform/resource/after-ecj/ExtensionMethodSuppress.java, test/transform/resource/before/ExtensionMethodNames.java, test/transform/resource/before/ExtensionMethodSuppress.java, test/transform/resource/messages-ecj/ExtensionMethodSuppress.java.messages
This PR fixes #2261. The branch is based on #2558 because it requires that fix to pass tests. If that one gets merged, this PR should only contain one commit. If you know a better way to create a dependent PR, please let me know and I will modify this one. 
The javac handler for `@ExtensionMethod` tried to detect static method access e.g. `Test.staticMethod()` by comparing the name of the receiver with the type name of the receiver. While that excluded all these calls properly it also excludes valid calls like 
```
Test Test = new Test();
Test.extension();
```
To solve that, lombok now uses the resolution information to figure out if `Test` is a varaible or a class. I also removed one resolution call by reusing the result of the first one, that should slightly improve the performance.
=> Detect static method access properly

src/delombok/lombok/delombok/Delombok.java, src/stubs/com/sun/tools/javac/main/Arguments.java
This PR fixes #2586.
The `init` method signature changed from `init(String, String...)` to `init(String, Iterable<String>)`.
=> Add Java 15 support for delombok

AUTHORS, src/core/lombok/core/configuration/CheckerFrameworkVersion.java, test/stubs/org/checkerframework/checker/objectconstruction/qual/CalledMethods.java, test/stubs/org/checkerframework/checker/objectconstruction/qual/NotCalledMethods.java, test/transform/resource/after-delombok/CheckerFrameworkBuilder.java, test/transform/resource/after-delombok/CheckerFrameworkSuperBuilder.java, test/transform/resource/after-ecj/CheckerFrameworkBuilder.java, test/transform/resource/after-ecj/CheckerFrameworkSuperBuilder.java
This pull request updates the names of annotations used by the Checker Framework.
The old versions continue to be supported by the Checker Framework, but it's better to use the current version.
=> The Object Construction Checker has been renamed the Called Methods Checker

src/eclipseAgent/lombok/eclipse/agent/PatchJavadoc.java
At some point I removed this necessary null check...
Obviously the javadoc map can be `null` if lombok does not add any comments. Returning `null` is save here, the original method does that too and lombok only tries to add the comment if that happens. Without this fix eclipse will write an error to the error log everytime someone tries to show the javadoc comment e.g. during code completion.
=> Add missing null check

src/core/lombok/javac/handlers/JavacHandlerUtil.java, src/stubs/com/sun/tools/javac/code/Symbol.java
The `adr` field has to be set for the new `VarSymbol`. The field should be there in every supported Java version, it is unchanged for 13 years.
This is a potential fix for #2612 .
=> VarSymbol.adr is required for flow analysis in Netbeans

src/core/lombok/javac/handlers/HandleBuilder.java, test/transform/resource/after-delombok/BuilderWithToBuilder.java, test/transform/resource/after-ecj/BuilderWithToBuilder.java, test/transform/resource/before/BuilderWithToBuilder.java
This PR fixes #2657.
The latest refactoring introduced this error by using the wrong field. I also added a test case to cover `@Builder(toBuilder=true)` on a static method.
=> Use the correct field to query parent type parameters in Builder

src/core/lombok/javac/JavacAST.java
I did some testing with the current edge release, and found a bug:
[The fix](https://github.com/rzwitserloot/lombok/commit/e1f82ac4d132769cfc272dccfc916aeba7181718) for #2645 is not working when using [sbt subprojects](https://www.scala-sbt.org/1.x/docs/Multi-Project.html).
In my case I have a subproject, which pulls in and uses lombok, and a parent (root) project (which depends on the subproject).
Now when running sbt in the root project and start compiling that root project, which in turn also compiles the subproject, the `lombok.config` (located in the subproject) is, again, ignored, resulting in compiling errors in the subproject.
After some debugging it turns out that the URI reported by sbt for the subproject has the format:
``` …
```
=> Fixing reading files in sbt 1.4+ subprojects

src/eclipseAgent/lombok/eclipse/agent/PatchExtensionMethod.java, test/transform/resource/after-delombok/ExtensionMethodFunctional.java, test/transform/resource/after-delombok/ExtensionMethodGeneric.java, test/transform/resource/after-ecj/ExtensionMethodFunctional.java, test/transform/resource/after-ecj/ExtensionMethodGeneric.java, test/transform/resource/before/ExtensionMethodFunctional.java, test/transform/resource/before/ExtensionMethodGeneric.java
This PR fixes #2648.
In Java >= 8 ecj uses the inference context to resolve the generic information. This one is already set before lombok tries rewrite the method call. Simply copying the information does not cover all the different cases but reseting the inference contexts and running type inference again does.
=> Reset inference context for extension methods

doc/changelog.markdown
Seems like this was miss during feature release.
=> Add new cache hashCode feature to changelog

src/core/lombok/eclipse/handlers/EclipseHandlerUtil.java
If the propterty `memberValuePaitName` is not present the reflection field is `null` which leads to a NPE. I added a simple `null` check and moved the copy code to a new method instead of repeating it three times.
=> Replace duplicate code with new method, add null check

src/core/lombok/core/handlers/HandlerUtil.java, src/core/lombok/eclipse/handlers/EclipseHandlerUtil.java, src/core/lombok/javac/handlers/JavacHandlerUtil.java, test/transform/resource/after-delombok/BuilderJavadoc.java, test/transform/resource/after-delombok/JavadocMultiline.java, test/transform/resource/after-ecj/BuilderJavadoc.java, test/transform/resource/after-ecj/JavadocMultiline.java, test/transform/resource/before/JavadocMultiline.java
This PR fixes #2443.
I have a few general improvements for the javadoc handling in mind but it will take some time until I have implemented them.
=> Remove multiline Javadoc tags

src/core/lombok/ConfigurationKeys.java
As of line 275 the default value for `lombok.toString.callSuper` is `skip`, while line 177 states the default to be `warn`. As far as I read the code `skip` is the correct default here.
=> Fix inconsistency in lombok.toString.callSuper doc

src/core/lombok/eclipse/handlers/HandleEqualsAndHashCode.java, src/core/lombok/javac/handlers/HandleEqualsAndHashCode.java, test/transform/resource/after-delombok/DataWithOverrideEqualsAndHashCode.java, test/transform/resource/after-ecj/DataWithOverrideEqualsAndHashCode.java, test/transform/resource/before/DataWithOverrideEqualsAndHashCode.java
This PR fixes #1064
The code that adds the warning for the missing super call now runs after the check for existing methods so it will only print it if lombok generates a method.
=> Only show super()-warning if lombok generates a method

src/core/lombok/eclipse/handlers/HandleSuperBuilder.java, src/core/lombok/javac/handlers/HandleSuperBuilder.java, test/transform/resource/after-delombok/CheckerFrameworkSuperBuilder.java, test/transform/resource/after-ecj/CheckerFrameworkSuperBuilder.java, test/transform/resource/after-ecj/NullAnnotatedCheckerFrameworkSuperBuilder.java
This PR fixes #2692
Lombok now adds `@SideEffectFree` in eclipse and `@Unique` for the `builder()` method in `javac`. I also fixed the `NullAnnotatedCheckerFrameworkSuperBuilder` test case.
=> Add missing checker annotations in SuperBuilder

src/core/lombok/javac/handlers/HandleExtensionMethod.java, test/transform/resource/after-delombok/ExtensionMethodChain.java, test/transform/resource/after-ecj/ExtensionMethodChain.java, test/transform/resource/before/ExtensionMethodChain.java
=> Handle inner method invocations first

src/eclipseAgent/lombok/eclipse/agent/PatchExtensionMethod.java, test/core/src/lombok/RunTestsViaEcj.java, test/transform/resource/after-ecj/ExtensionMethodNonStaticAccess.java, test/transform/resource/before/ExtensionMethodNonStaticAccess.java, test/transform/resource/messages-ecj/ExtensionMethodNonStaticAccess.java.messages
This PR fixes #2752
The `ProblemReporter` has an internal `ReferenceContext` state which gets cleared if an error was handled. If there is more than one error for the same method call the state is `null` for postponed messages. Lombok now stores this value and restores it if required.
=> Save problem handler state for postponed error handling

src/core/lombok/eclipse/handlers/HandleUtilityClass.java
This PR fixes #2756
`@UtilityClass` now uses the `SetGeneratedByVisitor` to set positions and generated markers.
=> Mark generated UtilityClass constructor as generated

src/core/lombok/eclipse/handlers/HandleSuperBuilder.java, test/transform/resource/after-delombok/SuperBuilderWithExistingConstuctor.java, test/transform/resource/after-ecj/SuperBuilderWithExistingConstuctor.java, test/transform/resource/before/SuperBuilderWithExistingConstuctor.java
Add `null` check to avoid NPE in Eclipse's `HandleSuperBuilder`.
Fixes #2704.
=> [fixes #2704] SuperBuilder: avoid NPE on existing constructors

src/core/lombok/javac/handlers/HandleSuperBuilder.java, test/transform/resource/after-delombok/SuperBuilderSingularCustomized.java, test/transform/resource/after-ecj/SuperBuilderSingularCustomized.java, test/transform/resource/before/SuperBuilderSingularCustomized.java
This PR fixes a NPE on a customized `@SuperBuilder` with `@Singular`, as discussed in #2701.
=> [fixes #2701] fix NPE on customized SuperBuilder with Singular

src/core/lombok/core/handlers/HandlerUtil.java
Also copy `@JacksonXmlElementWrapper` and `@JacksonXmlText` to setter methods, as discussed in #2654.
=> Add more Jackson annotations to the copy-to-setter list

AUTHORS, src/core/lombok/javac/handlers/HandleBuilderDefaultRemove.java, src/core/lombok/javac/handlers/HandleBuilderRemove.java, src/core/lombok/javac/handlers/HandleSuperBuilderRemove.java, test/transform/resource/after-delombok/BuilderAccessWithGetter.java, test/transform/resource/after-delombok/BuilderDefaultsWarnings.java, test/transform/resource/after-delombok/BuilderSingularNoAuto.java, test/transform/resource/after-delombok/BuilderSingularNoAutoWithSetterPrefix.java, test/transform/resource/after-delombok/JacksonizedSuperBuilderWithJsonDeserialize.java, test/transform/resource/after-ecj/BuilderAccessWithGetter.java, test/transform/resource/before/BuilderAccessWithGetter.java
Otherwise they may run after `HandleDelegate`. This is problematic as
`HandleDelegate` parses the compulation unit and `@Builder` may contain imports
(eg `AccessLevel`) that were already removed by other processors, eg `@Getter`.
fixes #2724
=> [fixes #2724] Increase priority of Builder annotation removal

src/core/lombok/eclipse/handlers/HandleBuilder.java, src/core/lombok/eclipse/handlers/HandleSuperBuilder.java, src/core/lombok/javac/handlers/HandleBuilder.java, src/core/lombok/javac/handlers/HandleSuperBuilder.java, test/transform/resource/after-delombok/SuperBuilderWithCustomBuilderClassName.java, test/transform/resource/after-ecj/SuperBuilderWithCustomBuilderClassName.java, test/transform/resource/before/SuperBuilderWithCustomBuilderClassName.java
`@SuperBuilder` now correctly considers `lombok.builder.className` when generating the `extends` clause for the abstract builder class.
This PR fixes #2647.
=> SuperBuilder: consider lombok.builder.className for builder extends clause

LICENSE
@mirabilos [noticed](https://groups.google.com/g/project-lombok/c/z2OAsdkX1VQ) that there are no license information of embedded dependencies. I used the format that is also used by [gradle](https://github.com/gradle/gradle/blob/master/LICENSE) so I think this should be fine.
=> Add licenses of embedded dependencies

src/core/lombok/javac/handlers/HandleVal.java, test/transform/resource/after-delombok/ValInLambda.java, test/transform/resource/after-ecj/ValInLambda.java, test/transform/resource/before/ValInLambda.java
This PR fixes #2787 by replacing `visitLocal` with `endVisitLocal` to delay the resolution.
Tested it on Java 8 and Java 14
=> Handle right hand side of assignment first

src/delombok/lombok/delombok/PrettyPrinter.java, test/pretty/resource/after/Record.java, test/pretty/resource/before/Record.java
This PR fixes the wrong position of the compact constructor if the record implements an interface as mentioned in #2775
=> Print compact constructor after class name

AUTHORS, src/core/lombok/ConfigurationKeys.java, src/core/lombok/StandardException.java, src/core/lombok/eclipse/handlers/HandleStandardException.java, src/core/lombok/experimental/StandardException.java, src/core/lombok/javac/handlers/HandleStandardException.java, src/stubs/com/sun/tools/javac/code/Symtab.java, test/transform/resource/after-delombok/StandardExceptions.java, test/transform/resource/before/StandardExceptions.java, website/templates/features/experimental/StandardException.html, website/templates/features/experimental/index.html, website/usageExamples/StandardExceptionExample_post.jpage, website/usageExamples/StandardExceptionExample_pre.jpage
Fixes #1559, related to #375 and discussed in [this thread](https://groups.google.com/u/2/g/project-lombok/c/x1DdJvG-PKc/m/zIbn1aLaCAAJ).
This is a pretty advanced attempt at implementing the proposed `@StandardException` feature (naming to be discussed). It turns the following:
```java
@StandardException
public class ExampleException extends Exception {
}
```
... into:
```java
public class ExampleException extends Exception {
public ExampleException() {
}
public ExampleException(String message) {
super(message);
}
public ExampleException(Throwable cause) {
super(cause);
}
public ExampleException(String message, Throwable cause) {
super(message, cause);
}
}
```
If one of those 4 constructors is already declared, the handlers skip it. Naturally, compilation fails if any of the parent …
=> @StandardException annotation for generating exception constructors

src/core/lombok/javac/handlers/HandleConstructor.java, src/core/lombok/javac/handlers/HandleGetter.java, src/core/lombok/javac/handlers/HandleSetter.java, src/core/lombok/javac/handlers/HandleSuperBuilder.java, src/core/lombok/javac/handlers/HandleUtilityClass.java, src/core/lombok/javac/handlers/HandleWith.java, src/core/lombok/javac/handlers/HandleWithBy.java, src/core/lombok/javac/handlers/JavacHandlerUtil.java, src/utils/lombok/permit/Permit.java, test/core/src/lombok/RunTestsViaDelombok.java
This PR fixes #1538.
As discussed in #1538 the inject methods now use the `javac` enter code to add the new types/methods/fields. As this stuff is a little bit difficult to test I added a hardcoded annotation processor to `Delombok.java#L721` that I used for debugging.
I tested these changes using Java 8 and 14 and also checked that it works in Netbeans.
=> Use Enter and MemberEnter to update type mirrors

src/core/lombok/eclipse/EclipseAST.java, src/core/lombok/eclipse/TransformEclipseAST.java, src/core/lombok/eclipse/handlers/EclipseHandlerUtil.java, src/core/lombok/eclipse/handlers/HandleBuilder.java
It seems like `compilationUnit.getContents()` is not always cached and can trigger some file system operations. By reusing the data that is already loaded by the parser we can avoid that.
=> Avoid reading file from disk by reusing the parser source

src/core/lombok/javac/JavacResolution.java, src/stubs/com/sun/tools/javac/comp/ArgumentAttr.java
This PR fixes #2460, fixes #2462
In Java 9 the class `ArgumentAttr` was added to address some performance issues (https://github.com/openjdk/jdk/commit/981c6dc2989b66f3691090c9f81e23d2b0a00087). This class uses an internal cache that gets polluted by lomboks resoultion calls. I fixed that by storing the original cache value and restoring it after lomboks resolution calls.
I tested it using Java 8, 11 and 16, I also validated that the `javac` performance improvements are not affected by these changes.
For some reaseon the fixed bugs only occurs during normal compilation and not in test cases...
=> Cleanup internal argument cache

src/utils/lombok/javac/TreeMirrorMaker.java, test/transform/resource/after-delombok/ValSwitchExpression.java, test/transform/resource/after-ecj/ValSwitchExpression.java, test/transform/resource/before/ValSwitchExpression.java
This PR fixes #2624.
In Java 14 and 15 the `TreeCopier` creates inconsistent copies by duplicating `JCCase#body` instead of using the one that is already part of `JCCase#stats`. This bug/problem was fixed in Java 16: https://github.com/openjdk/jdk/commit/b37228e11fc69128b8172968e6b1049bcb9cb994. 
Instead of overriding the `TreeCopier` code and using reflection to fix `JCCase#body` this PR simply discards multiple targets in the result map. As the right part of `JCCase` gets copied first this fixes the actual problem.
=> Resolve variables in switch expressions

src/core/lombok/SneakyThrows.java
Found an error in the documentation in the file SneakyThrows.java.
The documentation on the website shows the correct return value.
=> SneakyThrows.java fix typo - return String instead void

src/eclipseAgent/lombok/launch/PatchFixesHider.java
This PR fixes #2926
The "Use modifier 'final' where possible" cleanup have to find the generated setter to properly detect that there is something that can modify the varaible. I also checked the other cleanups and it seems like this one is the only one that needs this exception.
=> Fix "Use modifier 'final' where possible" cleanup

src/utils/lombok/javac/TreeMirrorMaker.java, test/transform/resource/after-delombok/ValAnonymousSubclassSelfReference.java, test/transform/resource/after-ecj/ValAnonymousSubclassSelfReference.java, test/transform/resource/before/ValAnonymousSubclassSelfReference.java
This PR fixes #2420
The `TreeMirrorMaker` has some special code to copy symbols and types for variables in some cases. It seems like that it is also required to copy the `vartype` field if we copy the other stuff. It also works if the whole symbol/type copy block gets removed but that most likely reintroduce the original issue even if I was unable to reproduce it.
**Edit**
Added a visitor to also copy reference types
=> Also copy vartype.type in TreeMirrorMaker

src/core/lombok/javac/handlers/JavacHandlerUtil.java
This PR fixes #2863
Sharing `JCPrimitiveTypeTree` between tree nodes causes a NPE in NetBeans because it clears the `type` for some trees which also clears the type of the original variable declaration.
=> Clone primitive types

src/core/lombok/javac/handlers/HandleNonNull.java, src/delombok/lombok/delombok/Delombok.java, test/core/src/lombok/RunTestsViaDelombok.java
This PR fixes #2907
We can simply keep the parameters of the constructor to also keep the symbols.
I also adjusted the automatic symbol check to catch problems like this one.
=> Keep record compact constructor parameters

src/core/lombok/eclipse/handlers/EclipseHandlerUtil.java, src/core/lombok/eclipse/handlers/HandleVal.java, src/eclipseAgent/lombok/eclipse/agent/PatchVal.java, test/transform/resource/before/ValAnonymousSubclassSelfReference.java
This PR fixes #2972
The original bug was fixed by generating a `SingleTypeReference` instead of a `QualifiedTypeReference`. After that I noticed that the code completion is broken for `val`. This could be fixed by reusing the original patch code and move the new stuff to the patch part.
=> Move 'val' -> 'final var' code to patch method

src/core/lombok/eclipse/handlers/EclipseHandlerUtil.java, src/eclipseAgent/lombok/eclipse/agent/EclipsePatcher.java, src/eclipseAgent/lombok/eclipse/agent/PatchJavadoc.java, src/eclipseAgent/lombok/launch/PatchFixesHider.java
This PR fixes #2950
For the syntax highlighting I added the language server `SemanticTokensVisitor` to hide generated lombok nodes. I also renamed the patch method because it now handles more things than only refactorings.
To fix the javadoc I added patches for the language server copy of `JavadocContentAccess2`, they modified it to also support markdown. I also had to add some reflection code to call `CompilationUnit::originalFromClone` because the language server implementation uses a working copy for compilation and the original compilation unit to resolve the comments.
=> Add syntax highlighting and javadoc to language server (VSCode)

src/eclipseAgent/lombok/eclipse/agent/EclipsePatcher.java
This might be related to #2509
**Without the fix:** 
`@EqualsAndHashCode` is blue 
After adding a new line half of the class looses its highlighting
**After the fix:**
=> Fix syntax highlighting for EqualsAndHashCode

src/utils/lombok/javac/Javac.java
This PR fixes #3043
This problem was not discovered by the test cases because the `CommentCollectingParser` always extends the `EndPosParser` which obviously always sets end positions. I tried change the parent to `Parser` but that breaks the test cases because `CapturingDiagnosticListener` and `PrettyPrinter` need the positions.
=> Add null check for end positions

src/core/lombok/javac/handlers/HandleBuilder.java, src/core/lombok/javac/handlers/HandleSuperBuilder.java, test/transform/resource/after-delombok/BuilderDefaultsTargetTyping.java, test/transform/resource/after-delombok/SuperBuilderWithDefaultsAndTargetTyping.java, test/transform/resource/after-ecj/BuilderDefaultsTargetTyping.java, test/transform/resource/after-ecj/SuperBuilderWithDefaultsAndTargetTyping.java, test/transform/resource/before/BuilderDefaultsTargetTyping.java, test/transform/resource/before/SuperBuilderWithDefaultsAndTargetTyping.java
This PR fixes #3036
The unique position cache in `ArgumentAttr` cannot handle generated lombok nodes because they all share the same position. To not break it lombok now keeps the original position of the initializer.
Tested in Java 6, 8, 11,17 and Netbeans
=> Keep builder default initializer position

src/eclipseAgent/lombok/eclipse/agent/PatchVal.java
This PR fixes #3000
Lombok now generates a new type reference for the `val` marker annotation.
=> Generate new type reference for val marker annotation

src/core/lombok/eclipse/handlers/singulars/EclipseGuavaSingularizer.java, src/core/lombok/javac/handlers/singulars/JavacGuavaSingularizer.java, test/transform/resource/after-delombok/SuperBuilderSingularToBuilderGuava.java, test/transform/resource/after-ecj/SuperBuilderSingularToBuilderGuava.java, test/transform/resource/before/SuperBuilderSingularToBuilderGuava.java
This PR fixes some issues with `@SuperBuilder(toBuilder=true)` and Guava type names when generating the static helper method `$fillValuesFromInstanceIntoBuilder`.
This fixes #3070.
=> Fix Guava type names for SuperBuilder's toBuilder

src/core/lombok/core/configuration/CheckerFrameworkVersion.java, src/core/lombok/eclipse/handlers/EclipseHandlerUtil.java, src/core/lombok/eclipse/handlers/EclipseSingularsRecipes.java, src/core/lombok/eclipse/handlers/HandleSetter.java, src/core/lombok/eclipse/handlers/HandleSuperBuilder.java, src/core/lombok/eclipse/handlers/singulars/EclipseGuavaSingularizer.java, src/core/lombok/eclipse/handlers/singulars/EclipseJavaUtilListSetSingularizer.java, src/core/lombok/eclipse/handlers/singulars/EclipseJavaUtilMapSingularizer.java, src/core/lombok/javac/handlers/HandleSetter.java, src/core/lombok/javac/handlers/HandleSuperBuilder.java, src/core/lombok/javac/handlers/JavacHandlerUtil.java, src/core/lombok/javac/handlers/JavacSingularsRecipes.java, test/stubs/org/checkerframework/common/returnsreceiver/qual/This.java, test/transform/resource/after-delombok/CheckerFrameworkBasic.java, test/transform/resource/after-delombok/CheckerFrameworkBuilder.java, test/transform/resource/after-delombok/CheckerFrameworkSuperBuilder.java, test/transform/resource/after-ecj/CheckerFrameworkBasic.java, test/transform/resource/after-ecj/CheckerFrameworkBuilder.java, test/transform/resource/after-ecj/CheckerFrameworkSuperBuilder.java
This PR makes lombok generate Checker Framework's `@This` as type annotation, as it is defined by the Checker Framework.
It fixes #3081.
Furthermore, it generates `@This` and `@CalledMethods` already starting at CF version 3.10.0. These annotations may even be added earlier, but I did not go through all the CF history; I guess 3.10.0 is far enough in the past. ;)
Note: I have no idea why these changes break the idempotent tests for `CheckerFrameworkSuperBuilder` and `CheckerFrameworkBasic`, but `CheckerFrameworkBuilder` works.
=> Make CheckerFramework's This a type annotation

src/core/lombok/javac/handlers/HandleUtilityClass.java, test/transform/resource/after-delombok/UtilityClass.java, test/transform/resource/after-ecj/UtilityClass.java, test/transform/resource/before/UtilityClass.java
This PR fixes #3097
Inner classes reference the outer type, if we convert it into a static class we have to remove this reference because `javac` > 8 checks if this reference is valid.
=> Update inner class type when creating a static class

src/core/lombok/javac/handlers/HandleBuilderDefaultRemove.java, src/core/lombok/javac/handlers/HandleSuperBuilder.java, test/transform/resource/after-delombok/ConstructorsWithSuperBuilderDefaults.java, test/transform/resource/after-delombok/SuperBuilderWithDefaultsAndTargetTyping.java, test/transform/resource/after-ecj/ConstructorsWithSuperBuilderDefaults.java, test/transform/resource/before/ConstructorsWithSuperBuilderDefaults.java
This PR fixes #3053
Some time ago `@NoArgsConstructor` was changed to also use `@Builder.Default` initializers. Unlike `@Builder`, `@SuperBuilder` removes this annotation while doing its work and `@NoArgsConstructor` is unable to detect these fields.
=> Delay default annotation removal

src/core/lombok/eclipse/handlers/HandleConstructor.java, src/core/lombok/eclipse/handlers/HandleSetter.java, src/utils/lombok/eclipse/Eclipse.java
This PR fixes #3133
The bits are required to generate the correct bytecode.
=> Add annotation bits to annotation copy targets

src/eclipseAgent/lombok/eclipse/agent/EclipsePatcher.java, src/eclipseAgent/lombok/launch/PatchFixesHider.java
This PR fixes #3134
Eclipse added a new `findByNode` method to `LinkedNodeFinder`. Because both use the same name we need to include the parameters in the search to find the correct one. I also added a patch for the new method.
=> Search patched method also by parameters

AUTHORS, src/core/lombok/javac/handlers/HandleLog.java, test/transform/resource/after-delombok/LoggerFlogger.java, test/transform/resource/after-delombok/LoggerJBossLog.java, test/transform/resource/after-delombok/LoggerJul.java, test/transform/resource/after-delombok/LoggerLog4j.java, test/transform/resource/after-delombok/LoggerLog4j2.java, test/transform/resource/after-delombok/LoggerSlf4j.java, test/transform/resource/after-ecj/LoggerFlogger.java, test/transform/resource/after-ecj/LoggerJBossLog.java, test/transform/resource/after-ecj/LoggerJul.java, test/transform/resource/after-ecj/LoggerLog4j.java, test/transform/resource/after-ecj/LoggerLog4j2.java, test/transform/resource/after-ecj/LoggerSlf4j.java, test/transform/resource/before/LoggerFlogger.java, test/transform/resource/before/LoggerJBossLog.java, test/transform/resource/before/LoggerJul.java, test/transform/resource/before/LoggerLog4j.java, test/transform/resource/before/LoggerLog4j2.java, test/transform/resource/before/LoggerSlf4j.java
=> Fix enum logging

src/eclipseAgent/lombok/eclipse/agent/PatchExtensionMethod.java, test/transform/resource/after-delombok/ExtensionMethodFunctional.java, test/transform/resource/after-ecj/ExtensionMethodFunctional.java, test/transform/resource/before/ExtensionMethodFunctional.java
This PR fixes #3153
A conditional expression with at least one functional part must be treated in the same way as a functional expression.
=> Improve the handling of ExtensionMethod arguments

website/templates/features/experimental/StandardException.html
Closed parenthesis in the StandardException page of the website.
=> Fix typo in StandardException documentation

website/templates/setup/vscode.html
Per (https://devblogs.microsoft.com/java/java-on-visual-studio-code-update-july-2022/), the latest Extension for Pack has provided built-in support for Lombok.
In addition, the community-developed Lombok extension has entered a maintenance mode, the original author has moved on from the project. Microsoft is going to maintain the project from now on (The extension has been transferred to Microsoft)
Thanks1
=> Update VS Code page for Lombok support

buildScripts/ivy.xml, src/delombok/lombok/delombok/PrettyPrinter.java, src/utils/lombok/javac/JavacTreeMaker.java, test/pretty/resource/after/RecordPattern.java, test/pretty/resource/after/Switch19.java, test/pretty/resource/before/RecordPattern.java, test/pretty/resource/before/Switch19.java
This PR requires a new lombok.patcher release (0.46) with ASM 9.3.
Issues: #3211
=> Add support for JDK 19

src/core/lombok/eclipse/handlers/HandleBuilder.java, src/core/lombok/eclipse/handlers/HandleSuperBuilder.java
This PR fixes #3181
@snjeza already provided a fix and I also added it to `@SuperBuilder`. The `.clone()` is required because the `SelectionEngine` compares identities to find the correct field and fails if there are multiple fields sharing the same array.
=> Copy field name arrays in (Super)Builder

src/core/lombok/eclipse/handlers/HandleSuperBuilder.java, src/core/lombok/javac/handlers/HandleSuperBuilder.java, test/transform/resource/after-delombok/SuperBuilderNameClashes.java, test/transform/resource/after-ecj/SuperBuilderNameClashes.java, test/transform/resource/before/SuperBuilderNameClashes.java
With this PR, `@SuperBuilder` checks for type argument name collisions also with `extends` and `implements` clauses. This fixes #3202.
For retrieving the `extends` clause in the javac handler, I had to use `Javac.getExtendsClause(classDecl))`, which does some tricks to get around access limitations for that method. When using `JCClassDecl.getImplementsClause()` this was not necessary at least in my setup (Java 11). I'm not sure if there might be access restrictions for that method (similar to the `getExtendsClause` method) in other Java version.
Does anyone know that? (No other handler uses that method, so there is no indication in the current sources...)
=> SuperBuilder: check extends/implements for collisions (fixes #3202)

src/core/lombok/eclipse/handlers/HandleExtensionMethod.java, src/core/lombok/javac/handlers/HandleExtensionMethod.java, src/core/lombok/javac/handlers/JavacHandlerUtil.java
Simple change to allow `@ExtensionMethod` on interfaces, done for javac and Eclipse handlers. Using this without any problems for almost two months now. (fixes #3259)
=> fixes #3259: allow @ExtensionMethod on interfaces

src/core/lombok/javac/JavacResolution.java, test/transform/resource/after-delombok/ValSuperDefaultMethod.java, test/transform/resource/after-ecj/ValSuperDefaultMethod.java, test/transform/resource/before/ValSuperDefaultMethod.java
This PR fixes #3242
Using `Type.noType` works as long as we do not need the parent class/interface. Lombok now uses the symbol type if it is available.
=> Use real type for enclosing class

src/core/lombok/AllArgsConstructor.java, src/core/lombok/NoArgsConstructor.java, src/core/lombok/RequiredArgsConstructor.java
Hi,
The existing links are dead.
Replaced them with the new links.
=> The URL to constructor has been corrected : replaced "Constructor" with "constructor"

src/core/lombok/eclipse/handlers/HandleBuilder.java, src/core/lombok/javac/handlers/HandleBuilder.java, test/transform/resource/after-delombok/BuilderDefaultsArray.java, test/transform/resource/after-ecj/BuilderDefaultsArray.java, test/transform/resource/before/BuilderDefaultsArray.java
This PR fixes #3306
It also includes changes for `javac`. Even if it worked there I think that the generated code should be valid.
=> Convert short array initializers to long version

src/core/lombok/javac/handlers/HandleUtilityClass.java, src/stubs/com/sun/tools/javac/code/Symbol.java, test/transform/resource/after-delombok/UtilityClassGeneric.java, test/transform/resource/after-ecj/UtilityClassGeneric.java, test/transform/resource/before/UtilityClassGeneric.java
This PR fixes #3274
`erasure_field` is part of the Symbol class since JDK6, should be safe to add it to the stubs.
=> Reset erasure_field of symbol

src/core/lombok/eclipse/handlers/EclipseHandlerUtil.java, test/transform/resource/after-ecj/LoggerFloggerRecord.java, test/transform/resource/after-ecj/LoggerSlf4jOnRecord.java, test/transform/resource/after-ecj/SynchronizedInRecord.java
This PR fixes #3327.
Eclipse expects that a record starts with the generated fields. As far as I know this only affects the string output.
=> Inject fields after generated record fields

src/core/lombok/core/configuration/BubblingConfigurationResolver.java
Hi,
looking up the parent of a `ConfigurationFile` is somewhat expensive and allocation "intense".
Overall it makes up for ~20% of allocations. While I have a different PR coming up that caches the result of `ConfigurationFile.parent` I wanted to split this from this PR, because I think it's actually wrong to lookup the parent if the bubbling stopped and should be imho discussed separately.
Let me know what you think.
Cheers,
Christoph
=> Avoid looking up parent if bubbling stopped

src/core/lombok/core/configuration/ConfigurationFile.java
Hi,
looking up the parent of a ConfigurationFile is somewhat expensive and allocation "intense". Overall this makes up for 20% of all allocations during compilation. With the patch applied I can reduce this to 0.13%
**Before**
**After**
Notice how the purple search highlights almost disappear from the latter screenshot.
I should note that the caching is somewhat suboptimal when no parent can be found because that would make the cache useless, but that's a) the minority of cases and b) should be happening even less with https://github.com/projectlombok/lombok/pull/3357 
Let me know what you think.
Cheers,
Christoph
=> Cache ConfigurationFile.parent()

src/eclipseAgent/lombok/eclipse/agent/EclipsePatcher.java, src/eclipseAgent/lombok/eclipse/agent/PatchExtensionMethod.java, src/eclipseAgent/lombok/launch/PatchFixesHider.java, test/eclipse/resource/findreferences/extensionMethod/Extension.java, test/eclipse/resource/findreferences/extensionMethod/Usage.java, test/eclipse/resource/rename/extensionMethod/after/Extension.java, test/eclipse/resource/rename/extensionMethod/after/Usage.java, test/eclipse/resource/rename/extensionMethod/before/Extension.java, test/eclipse/resource/rename/extensionMethod/before/Usage.java, test/eclipse/src/lombok/eclipse/EclipseTests.java, test/eclipse/src/lombok/eclipse/SetupBeforeAfterTest.java, test/eclipse/src/lombok/eclipse/refactoring/RenameTest.java, test/eclipse/src/lombok/eclipse/references/FindReferencesTest.java
This PR fixes #3373
To find references eclipse uses an index that is based on method parameters. A extension method definition always has one parameter more than the reference. To find all matching methods the patch modifies the search pattern to always assume varargs. The search logic removes non-matching methods in a later step.
There might be some unintended side effects...
=> Find references for extension methods

src/eclipseAgent/lombok/eclipse/agent/PatchExtensionMethod.java, src/eclipseAgent/lombok/launch/PatchFixesHider.java
#3376 added a method that uses a eclipse only class in its signature. This breaks ecj. This PR replaces the type in the signature with `j.l.Object`.
=> Remove eclipse specific classes in ExtensionMethod patch signatures

src/core/lombok/javac/handlers/HandleEqualsAndHashCode.java, src/core/lombok/javac/handlers/HandleToString.java, src/core/lombok/javac/handlers/JavacHandlerUtil.java, src/utils/lombok/permit/Permit.java, test/transform/resource/after-delombok/ToStringArray.java, test/transform/resource/after-delombok/ToStringArrayTypeAnnotations.java, test/transform/resource/after-ecj/ToStringArray.java, test/transform/resource/after-ecj/ToStringArrayTypeAnnotations.java, test/transform/resource/before/ToStringArray.java, test/transform/resource/before/ToStringArrayTypeAnnotations.java
This PR fixes #3416 
I also replaced the reflection code for type annotations in HandleEqualsAndHashcode with the handle methods and refactored the handler to use static final fields (allows JVM optimizations) and method guards (no exception for Java < 8).
The last commit fixes a problem with the Zulu JDK and the removal of record comopenent annotations.
=> Ignore annotations during array detection 

src/core/lombok/javac/JavacAST.java, src/core/lombok/javac/JavacTransformer.java
Hi,
I've noticed that the creation of the error logger is quite intense.
The idea of this PR is to avoid the creation of the error logger repeatedly for every compilation unit. It's same throughout anyhow. By that, we can avoid the reflective overhead and avoid the corresponding repeated expensive exceptions that are caused by JDK 11 having a few things available on the parent `AbstractLogger` rather than directly in `Log`. The stuff still currently still works because the lookup on the parent classes is successful (if you're asking yourself if there is a problem underneath why those methods are created in the first place). But the ones on `Log` cause the exceptions (that are silently caught).
Let me know what you think.
Cheers,
Christoph
=> Prevent repeated expensive creation of error logger

src/core/lombok/ConfigurationKeys.java, src/core/lombok/eclipse/handlers/EclipseHandlerUtil.java, src/core/lombok/javac/handlers/JavacHandlerUtil.java, test/stubs/jakarta/annotation/Generated.java, test/stubs/javax/annotation/Generated.java, test/transform/resource/after-delombok/GeneratedJavaxJakarta.java, test/transform/resource/after-delombok/GeneratedJavaxOnLombokOn.java, test/transform/resource/after-delombok/GeneratedOn.java, test/transform/resource/after-ecj/GeneratedJavaxJakarta.java, test/transform/resource/after-ecj/GeneratedOn.java, test/transform/resource/before/EqualsAndHashCodeWithSomeExistingMethods.java, test/transform/resource/before/GeneratedJavaxJakarta.java, test/transform/resource/before/GeneratedJavaxOnLombokOn.java, test/transform/resource/before/GeneratedOffJavaxOn.java, test/transform/resource/before/GeneratedOn.java, test/transform/resource/messages-delombok/EqualsAndHashCodeWithSomeExistingMethods.java.messages, test/transform/resource/messages-ecj/EqualsAndHashCodeWithSomeExistingMethods.java.messages
This PR fixes #3248
I also removed the source directive in a completly unrelated testcase, added a new testcase for the deprecated configuration key and enabled the `javax.annotation.Generated` testcases for java 9+.
=> Add support for jakarta generated annotation

src/eclipseAgent/lombok/eclipse/agent/PatchExtensionMethod.java, test/transform/resource/after-delombok/ExtensionMethodWidening.java, test/transform/resource/after-ecj/ExtensionMethodWidening.java, test/transform/resource/before/ExtensionMethodWidening.java
This PR fixes #3463
`Expression::computeConversion` can handle all these conversions for us.
=> Support argument widening for extension methods

website/templates/setup/intellij.html
Since 2023.2, the Lombok plugin is no longer bundled with IntelliJ
(see https://github.com/JetBrains/intellij-community/commit/654a84f27f2ffec61164bdace5fb7b0e4c88f285)
=> Update intellij plugin setup instructions for IntelliJ 2023.2

src/core/lombok/javac/JavacAugments.java, src/core/lombok/javac/handlers/HandleGetter.java, src/core/lombok/javac/handlers/JavacHandlerUtil.java, test/transform/resource/after-delombok/GetterLazyArguments.java, test/transform/resource/after-delombok/GetterLazyErrorPosition.java, test/transform/resource/after-ecj/GetterLazyArguments.java, test/transform/resource/before/GetterLazyArguments.java, test/transform/resource/before/GetterLazyErrorPosition.java, test/transform/resource/messages-delombok/GetterLazyErrorPosition.java.messages, test/transform/resource/messages-idempotent/GetterLazyErrorPosition.java.messages
This PR fixes #3481 and fixes #3448 and fixes #3314
`javac` uses the class `UniquePos` to cache method argument types. This leads to problems for generated nodes that share the same position.
We only handled that case for direct method invocations and not nested ones as reported in the linked issues. Simply keeping the original position for the whole initializer fixes this problem. This also leads to generated error messages for the initializer and not the getter annotation which is a nice side effect.
=> Keep initializer position for lazy getter

src/core/lombok/eclipse/handlers/HandleGetter.java, src/core/lombok/javac/handlers/HandleGetter.java, test/transform/resource/after-delombok/GetterEnumConstant.java, test/transform/resource/after-ecj/GetterEnumConstant.java, test/transform/resource/before/GetterEnumConstant.java, test/transform/resource/messages-delombok/GetterEnumConstant.java.messages, test/transform/resource/messages-ecj/GetterEnumConstant.java.messages
This PR fixes #3427
This is a breaking change for `javac` but I cannot imagine why someone want to generate a static getter for an enum member.
=> Remove javac support for getter on enum members

src/core/lombok/eclipse/EcjAugments.java, src/core/lombok/eclipse/TransformEclipseAST.java, src/core/lombok/eclipse/TransformationState.java, src/eclipseAgent/lombok/eclipse/agent/EclipsePatcher.java
This PR fixes #3540
Storing the state in a `WeakHashMap` creates to much work for the garbage collector and eclipse crashes if there are a lot of parses. Lombok now also skips `module-info.java` files, there is nothing in these files we care about.
=> Store transformation state in CompilationUnit

src/eclipseAgent/lombok/eclipse/agent/EclipsePatcher.java, src/eclipseAgent/lombok/launch/PatchFixesHider.java, test/eclipse/resource/inline/getter/after/InlineGetter.java, test/eclipse/resource/inline/getter/before/InlineGetter.java, test/eclipse/resource/inline/setter/after/InlineSetter.java, test/eclipse/resource/inline/setter/before/InlineSetter.java, test/eclipse/src/lombok/eclipse/EclipseTests.java, test/eclipse/src/lombok/eclipse/refactoring/InlineTest.java
=> Support inlining in eclipse

src/eclipseAgent/lombok/eclipse/agent/EclipsePatcher.java, src/eclipseAgent/lombok/launch/PatchFixesHider.java, src/launch/lombok/launch/ShadowClassLoader.java
This PR fixes #3440
I finished this some time ago but somehow forgot to create a PR. This is my third (?) attempt to properly fix the classloading problems caused by the seperation of the eclipse bundles. In some cases the last version called the prepend method to late.
=> Prepend jdt.core classloader to the parser classloader

src/core/lombok/eclipse/TransformEclipseAST.java, src/eclipseAgent/lombok/eclipse/agent/EclipsePatcher.java, src/eclipseAgent/lombok/launch/PatchFixesHider.java, test/eclipse/resource/rename/data/after/A.java, test/eclipse/resource/rename/data/before/A.java, test/eclipse/resource/rename/nestedClass/after/A.java, test/eclipse/resource/rename/nestedClass/before/A.java, test/eclipse/src/lombok/eclipse/refactoring/RenameTest.java
This PR fixes #1758
The old patch method exploited the fact that a field as result for a method search is never valid to indirectly detect lombok-generated nodes. Instead of extending this approach and adding support for classes, I decided to redesign it. Lombok now removes the nodes at an earlier stage, which allows the use of the normal generated flags.
=> Remove generated nodes in search results

AUTHORS, doc/changelog.markdown, src/eclipseAgent/lombok/eclipse/agent/EclipsePatcher.java
Basically the same fix as in #3079. Just new coordinates for the maven plugin.
Was reported over at [Jasper-report-maven-plugin/issues/52](https://github.com/pro-crafting/Jasper-report-maven-plugin/issues/52)
=> Exclude the classloader for jasperreports-plugin

.github/workflows/ant.yml, buildScripts/ivy.xml, buildScripts/setup.ant.xml, buildScripts/tests.ant.xml, src/support/lombok/eclipse/dependencies/Child.java, src/support/lombok/eclipse/dependencies/DownloadEclipseDependencies.java, src/support/lombok/eclipse/dependencies/Provided.java, src/support/lombok/eclipse/dependencies/Repository.java, src/support/lombok/eclipse/dependencies/Required.java, src/support/lombok/eclipse/dependencies/UniqueQueue.java, src/support/lombok/eclipse/dependencies/Unit.java, src/support/lombok/eclipse/dependencies/UpdateSite.java
The new eclipse downloader resolves (most) dependencies automatically. It now also resolves composite repositories, enabling support for integration builds.
=> Add tests for Eclipse 2023-12 and integration builds

src/core/lombok/eclipse/EclipseNode.java, src/core/lombok/eclipse/handlers/EclipseHandlerUtil.java, src/core/lombok/javac/JavacNode.java, src/core/lombok/javac/handlers/JavacHandlerUtil.java, test/transform/resource/after-delombok/BuilderOnNestedClass.java, test/transform/resource/after-delombok/BuilderOnNestedRecord.java, test/transform/resource/after-delombok/WithOnNestedRecord.java, test/transform/resource/after-ecj/BuilderOnNestedClass.java, test/transform/resource/after-ecj/BuilderOnNestedRecord.java, test/transform/resource/after-ecj/WithOnNestedRecord.java, test/transform/resource/before/BuilderOnNestedClass.java, test/transform/resource/before/BuilderOnNestedRecord.java, test/transform/resource/before/WithOnNestedRecord.java
This PR fixes #3559 and fixes #3497
I think there might be an error in the  `isStatic` method as it always returns `true` for toplevel classes. Am I missing anything?
=> Treat nested records as static

src/core/lombok/eclipse/handlers/EclipseHandlerUtil.java, src/core/lombok/eclipse/handlers/HandleLocked.java, src/core/lombok/eclipse/handlers/HandleLockedRead.java, src/core/lombok/eclipse/handlers/HandleLockedWrite.java, src/core/lombok/eclipse/handlers/HandleSneakyThrows.java, src/core/lombok/eclipse/handlers/HandleSynchronized.java, test/core/src/lombok/AbstractRunTests.java, test/core/src/lombok/LombokTestSource.java, test/core/src/lombok/RunTestsViaDelombok.java, test/core/src/lombok/RunTestsViaEcj.java, test/core/src/lombok/TestParameters.java, test/core/src/lombok/TransformationResult.java, test/transform/resource/after-delombok/LockedInInitializer.java, test/transform/resource/after-delombok/SneakyThrowsInInitializer.java, test/transform/resource/after-delombok/SynchronizedInInitializer.java, test/transform/resource/after-ecj/LockedInInitializer.java, test/transform/resource/after-ecj/SneakyThrowsInInitializer.java, test/transform/resource/after-ecj/SynchronizedInInitializer.java, test/transform/resource/before/LockedInInitializer.java, test/transform/resource/before/SneakyThrowsInInitializer.java, test/transform/resource/before/SynchronizedInInitializer.java
This PR fixes #1443
The eclipse parser disables diet parse for field initializers, and if one of these initializers contains an anonymous type, it may also contain a method with a lombok annotation. In some cases, eclipse will resolve the bindings after the diet parse and lombok will generate unresolved code. To prevent this I added some code to identify and handle this case.
I was unable to reproduce this problem in an automated full eclipse test but I added a new source directive to compare the diet result.
=> Handle field initializer in diet mode

src/eclipseAgent/lombok/eclipse/agent/EclipsePatcher.java, src/eclipseAgent/lombok/launch/PatchFixesHider.java, test/eclipse/resource/noerrors/fieldNameConstantsInAnnotation/Annotation.java, test/eclipse/resource/noerrors/fieldNameConstantsInAnnotation/Constants.java, test/eclipse/resource/noerrors/fieldNameConstantsInAnnotation/Usage.java, test/eclipse/src/lombok/eclipse/EclipseRunner.java, test/eclipse/src/lombok/eclipse/EclipseTests.java, test/eclipse/src/lombok/eclipse/RefactoringUtils.java, test/eclipse/src/lombok/eclipse/SetupBeforeAfterTest.java, test/eclipse/src/lombok/eclipse/SetupSingleFileTest.java, test/eclipse/src/lombok/eclipse/SetupTest.java, test/eclipse/src/lombok/eclipse/cleanup/CleanupTest.java, test/eclipse/src/lombok/eclipse/compile/NoErrorsTest.java, test/eclipse/src/lombok/eclipse/edit/SelectTest.java, test/eclipse/src/lombok/eclipse/refactoring/ExtractInterfaceTest.java, test/eclipse/src/lombok/eclipse/refactoring/InlineTest.java, test/eclipse/src/lombok/eclipse/refactoring/RenameTest.java, test/eclipse/src/lombok/eclipse/references/FindReferencesTest.java
This PR fixes #3529 
Eclipse copies the field initializer source code if it is a constant. For generated nodes we have to read it from the ast node and not from the source file.
I also added a bunch of missing license headers in a seperate commit.
=> Set real field initializer source in eclipse

src/core/lombok/javac/handlers/HandleSuperBuilder.java, test/transform/resource/after-delombok/SuperBuilderWithAnnotatedTypeParam.java, test/transform/resource/after-ecj/SuperBuilderWithAnnotatedTypeParam.java, test/transform/resource/before/SuperBuilderWithAnnotatedTypeParam.java
`@SuperBuilder`'s handler was missing a case for annotated types in the extends clause. This fixes #3592.
=> SuperBuilder: handle annotated types in extends clause for javac

buildScripts/setup.ant.xml
When trying to build from an intel MacBook with `ant -noinput dist`, it rejects my computer architecture and calls me a snowflake
```
Full eclipse testing requires downloading a native SWT binding.
This script knows how to download for OS = [mac, linux, or windows] and architecture = [aarch64 or x86-64].
You have something different, you unique snowflake you.
Your OS: "Mac OS X", Your arch: "x86_64".
```
The problem is that it expects a dash (`-`) but my mac reports an underscore (`_`), this is solved by adding `x86_64` alongside `x86-64`
=> Allow builds from intel MacBook

AUTHORS, src/core/lombok/bytecode/FixedClassWriter.java, src/core/lombok/bytecode/PreventNullAnalysisRemover.java, src/core/lombok/bytecode/SneakyThrowsRemover.java, test/bytecode/resource/PostCompilePreventNullAnalysis.java, test/bytecode/src/lombok/bytecode/TestPostCompiler.java
The SneakyThrowsRemover and PreventNullAnalysisRemover were leaving traces of the calls to lombok.Lombok.sneakyThrow and lombok.Lombok.preventNullAnalysis behind because they were using a constructor of ClassWriter which reuses the constant pool of the original class for performance optimizations. So although the calls to sneakyThrows and preventNullAnalysis get removed from the methods there were still entries in the constant pool for them. The constant pool will be regenerated with this change so that the entries for sneakyThrows and preventNullAnalysis gets removed.
Relevant javadoc of the ClassWriter contructor: https://asm.ow2.io/javadoc/org/objectweb/asm/ClassWriter.html#%3Cinit%3E(org.objectweb.asm.ClassReader,int)
Fixes #3601
=> Fix removal of SneakyThrows and PreventNullAnalysis from bytecode

website/templates/features/GetterSetter.html
Just a typo, it should say "fluent" instead of "chain" here.
=> [website] Fix typo on GetterSetter page

src/delombok/lombok/delombok/PrettyPrinter.java, test/pretty/resource/after/UnnamedVariables.java, test/pretty/resource/before/UnnamedVariables.java
This PR adds support for JEP 456 (Unnamed Variables & Patterns) in delombok. JEP 456 was integrated in JDK22.
=> Support unnamed variables

src/utils/lombok/eclipse/Eclipse.java, test/eclipse/src/lombok/eclipse/cleanup/CleanupTest.java
This PR fixes the two broken test steps
- The normal test failed because the old constructor of `CaseStatement` doesn't exists anymore. I also reworked the code a little bit to use static final fields.
- The integration test failed because the referenced class `CodeStyleCleanUp` was renamed to `CodeStyleCleanUpCore`.
=> Fix Eclipse-I tests

src/core/lombok/eclipse/handlers/HandleConstructor.java, src/core/lombok/eclipse/handlers/HandleGetter.java, src/core/lombok/eclipse/handlers/HandleSetter.java, src/core/lombok/javac/handlers/HandleConstructor.java, src/core/lombok/javac/handlers/HandleGetter.java, src/core/lombok/javac/handlers/HandleSetter.java, test/transform/resource/before/OnXFlagUsage.java, test/transform/resource/messages-delombok/OnXFlagUsage.java.messages, test/transform/resource/messages-ecj/OnXFlagUsage.java.messages
This PR fixes #2848
The configuration key was never supported (oops).
=> Support onX.flagUsage configuration key

src/core/lombok/core/handlers/HandlerUtil.java, src/core/lombok/eclipse/handlers/EclipseHandlerUtil.java, src/core/lombok/eclipse/handlers/HandleBuilder.java, src/core/lombok/eclipse/handlers/HandleConstructor.java, src/core/lombok/javac/handlers/HandleConstructor.java, test/transform/resource/after-delombok/BuilderConstructorJavadoc.java, test/transform/resource/after-delombok/BuilderJavadoc.java, test/transform/resource/after-delombok/BuilderWithDeprecated.java, test/transform/resource/after-delombok/ConstructorJavadoc.java, test/transform/resource/after-ecj/BuilderConstructorJavadoc.java, test/transform/resource/after-ecj/BuilderJavadoc.java, test/transform/resource/after-ecj/BuilderWithDeprecated.java, test/transform/resource/after-ecj/ConstructorJavadoc.java, test/transform/resource/before/BuilderConstructorJavadoc.java, test/transform/resource/before/ConstructorJavadoc.java
This PR fixes #933
Lombok now adds a javadoc comment to a generated constructor if there is any field with a description.
=> Add javadoc for generated constructors

src/core/lombok/Data.java
The javadoc on Data.java says it generates a constructor, which is the equivalent of `@RequiredArgsConstructor` behavior. In reality though, the constructor is only generated if no explicitly defined constructors (including explicit Lombok constructors) already exist. The behavior is expected and documented [here](https://projectlombok.org/features/Data).
The javadoc alone, however, often causes confusions, since there is no clear explanation on why the constructor in `@Data` may or may not be generated, which leads to a need of additional digging in Lombok documentation.
=> Update Javadoc for @Data

src/core/lombok/eclipse/handlers/HandleLockedUtil.java, src/core/lombok/eclipse/handlers/HandleLog.java, src/core/lombok/eclipse/handlers/HandleSynchronized.java, test/transform/resource/after-ecj/InjectField.java, test/transform/resource/after-ecj/LockedInInitializer.java, test/transform/resource/after-ecj/LockedInRecord.java, test/transform/resource/after-ecj/LockedPlain.java, test/transform/resource/after-ecj/LockedStaticMix.java, test/transform/resource/after-ecj/LockedTypeMismatch.java, test/transform/resource/after-ecj/LoggerCommons.java, test/transform/resource/after-ecj/LoggerConfig.java, test/transform/resource/after-ecj/LoggerCustom.java, test/transform/resource/after-ecj/LoggerCustomWithPackage.java, test/transform/resource/after-ecj/LoggerCustomWithTopicAndName.java, test/transform/resource/after-ecj/LoggerFlogger.java, test/transform/resource/after-ecj/LoggerFloggerRecord.java, test/transform/resource/after-ecj/LoggerJBossLog.java, test/transform/resource/after-ecj/LoggerJul.java, test/transform/resource/after-ecj/LoggerLog4j.java, test/transform/resource/after-ecj/LoggerLog4j2.java, test/transform/resource/after-ecj/LoggerSlf4j.java, test/transform/resource/after-ecj/LoggerSlf4jOnRecord.java, test/transform/resource/after-ecj/LoggerSlf4jTypes.java, test/transform/resource/after-ecj/LoggerSlf4jWithPackage.java, test/transform/resource/after-ecj/LoggerXSlf4j.java, test/transform/resource/after-ecj/SynchronizedInAnonymousClass.java, test/transform/resource/after-ecj/SynchronizedInInitializer.java, test/transform/resource/after-ecj/SynchronizedInRecord.java, test/transform/resource/after-ecj/SynchronizedPlain.java
This PR enables marking for fields generated by `@Log`, `@Synchronized` and `@Locked`. It was disabled years ago to fix a bug but it was never enabled again.
=> Mark injected fields as generated

src/core/lombok/eclipse/handlers/HandleStandardException.java, src/core/lombok/javac/handlers/HandleStandardException.java, test/transform/resource/after-delombok/StandardExceptionWithConstructor.java, test/transform/resource/after-delombok/StandardExceptions.java, test/transform/resource/after-ecj/StandardExceptionWithConstructor.java, test/transform/resource/after-ecj/StandardExceptions.java, test/transform/resource/before/StandardExceptionWithConstructor.java, test/transform/resource/messages-ecj/StandardExceptionWithConstructor.java.messages
This PR fixes the compilation error reported in #3665
=> Add cast for null arguments

src/delombok/lombok/delombok/DocCommentIntegrator.java, test/transform/resource/after-delombok/BuilderNestedJavadoc.java, test/transform/resource/after-ecj/BuilderNestedJavadoc.java, test/transform/resource/before/BuilderNestedJavadoc.java
This problem was reported in #2934 and #3112.
=> Generate javadoc for nested classes

doc/changelog.markdown, src/core/lombok/javac/handlers/HandleSuperBuilder.java, test/transform/resource/after-delombok/SuperBuilderWithArrayTypeParam.java, test/transform/resource/after-ecj/SuperBuilderWithArrayTypeParam.java, test/transform/resource/before/SuperBuilderWithArrayTypeParam.java
=> SuperBuilder: fix builder class extends clause for array type parameters

src/core/lombok/SneakyThrows.java
corrects a trivial error in the javadoc for SneakyThrows
=> Minor correction to SneakyThrows javadoc

website/usageExamples/experimental/FieldNameConstantsExample_pre.jpage
Just stumbled across this unnecessary import in the snippet: https://projectlombok.org/features/experimental/FieldNameConstants
=> [doc] remove unnecessary import in FieldNameConstants example

doc/changelog.markdown, src/eclipseAgent/lombok/eclipse/agent/EclipsePatcher.java
I am currently in the process of renaming the plugin from jasperreports-plugin to jasperreports-maven-plugin.
=> Exclude the classloader for jasperreports-maven-plugin due to a classloader conflict with ECJ

src/core/lombok/eclipse/handlers/EclipseHandlerUtil.java, src/core/lombok/eclipse/handlers/HandleConstructor.java, test/transform/resource/after-delombok/WeirdJavadoc.java, test/transform/resource/after-ecj/WeirdJavadoc.java, test/transform/resource/before/WeirdJavadoc.java
This PR fixes #3709
The regex should handle all the weird cases (until we add markdown javadoc support...)
=> Improve extraction of javadoc comments

src/core/lombok/eclipse/handlers/EclipseHandlerUtil.java, test/eclipse/resource/noerrors/builderJavadoc/BuilderJavadoc.java, test/eclipse/resource/noerrors/builderJavadoc/Usage.java, test/eclipse/src/lombok/eclipse/compile/NoErrorsTest.java
This PR fixes #3706.
I couldn't figure out why it is null in some cases, but added a test to make sure it didn't break again.
=> Add null check for compilation unit

AUTHORS, src/bindings/mapstruct/lombok/mapstruct/NotifierHider.java, src/launch/lombok/launch/AnnotationProcessor.java
Report to MapStruct that a type is completed when there aren't any Lombok annotations left on it. Lombok annotations are removed whenever a class is processed. This way, annotations which require multiple rounds to process are also correctly handled, and MapStruct processing will be delayed until Lombok completely finishes processing required types.
Fixes issues with e.g. @FieldNameConstants and @Builder (see #3116)
=> [fixes #3116] Add multi round support for mapstruct

.github/workflows/ant.yml, buildScripts/ivy.xml, buildScripts/setup.ant.xml, buildScripts/tests.ant.xml, src/support/lombok/eclipse/dependencies/DownloadEclipseDependencies.java, test/core/src/lombok/RunTestsViaEcj.java
This PR fixes #3728
I also added test targets for eclipse 2024-09 and removed the deprecated `inlineJsrBytecode` parameter.
=> Remove signature files from eclipse plugin jars

src/eclipseAgent/lombok/eclipse/agent/EclipsePatcher.java, src/eclipseAgent/lombok/launch/PatchFixesHider.java, test/eclipse/resource/noerrors/synchronizedUsage/ClassWithSynchronized.java, test/eclipse/resource/noerrors/synchronizedUsage/Usage.java, test/eclipse/src/lombok/eclipse/compile/NoErrorsTest.java
=> Patch SourceTypeConverter to avoid parsing empty strings

src/support/lombok/eclipse/dependencies/DownloadEclipseDependencies.java
This PR fixes the broken eclipse tests
=> Close ZipOutputStream in eclipse dependency downloader

AUTHORS, src/core/lombok/javac/handlers/HandleConstructor.java, src/core/lombok/javac/handlers/HandleEqualsAndHashCode.java, src/core/lombok/javac/handlers/HandleGetter.java, src/core/lombok/javac/handlers/HandleJacksonized.java, src/core/lombok/javac/handlers/HandleSetter.java, src/core/lombok/javac/handlers/HandleWith.java, src/core/lombok/javac/handlers/HandleWithBy.java, src/core/lombok/javac/handlers/JavacHandlerUtil.java, src/core/lombok/javac/handlers/JavacSingularsRecipes.java, src/delombok/lombok/delombok/Delombok.java, test/core/src/lombok/RunTestsViaDelombok.java
fixes: #3799 
1. Replaced the usage of the clone method (which performed a shallow copy) with [TreeCopier](https://github.com/openjdk/jdk/blob/807f6f7fb868240cba5ba117c7059216f69a53f9/src/jdk.compiler/share/classes/com/sun/tools/javac/tree/TreeCopier.java). This ensures a deep copy of annotations, preventing updates to copied annotations from affecting the original ones.
2. Updated instances in the codebase (e.g., [this location](https://github.com/projectlombok/lombok/blob/master/src/core/lombok/javac/handlers/JavacHandlerUtil.java#L1787)) where annotations were not being copied, ensuring the use of copyAnnotations.
Added a unit test using Delombok to verify that AST node positions remain unchanged before and after the Lombok annotation processor is applied, across all existing test …
=> fix: Don't alter the AST node positions of original code.

src/eclipseAgent/lombok/eclipse/agent/EclipsePatcher.java, src/eclipseAgent/lombok/launch/PatchFixesHider.java, test/eclipse/resource/extractvariable/multiple/after/A.java, test/eclipse/resource/extractvariable/multiple/before/A.java, test/eclipse/resource/extractvariable/single/after/A.java, test/eclipse/resource/extractvariable/single/before/A.java, test/eclipse/src/lombok/eclipse/EclipseTests.java, test/eclipse/src/lombok/eclipse/RefactoringUtils.java, test/eclipse/src/lombok/eclipse/refactoring/ExtractVariableTest.java
This PR fixes #3783
Eclipse tries to identify side effects and uses the source range to locate the method, which doesn't work for lombok generated methods. This patch introduces an alternative lookup method that is compatible with lombok.
=> Return generated node for side effect check

website/templates/setup/gradle.html
`.gradle.kts`, unlike `.gradle`, is using Kotlin instead of Groovy as the base of its scripting language. The old syntax is problematic in `.gradle.kts` becasue:
- Kotlin string cannot be wrapped by single quote, aka `'some string'` is not allowed and should be `"some string"` instead
- Kotlin requires brackets for method calling, aka `f someArg` is not allowed and should be `f(someArg)` instead
So I made some changes to the syntax so that the installation guide is valid for both `.gradle.kts`, unlike `.gradle`
build.gradle.kts:
build.gradle:
=> update gradle syntax to support both `.gradle` and `.gradle.kts`

src/core/lombok/eclipse/handlers/EclipseHandlerUtil.java, src/eclipseAgent/lombok/eclipse/agent/PatchDelegate.java, test/transform/resource/after-delombok/DelegateOnRecord.java, test/transform/resource/after-ecj/DelegateOnRecord.java, test/transform/resource/before/DelegateOnRecord.java
This PR fixes #3830
It already worked using `javac`, this PR only adds eclipse support and a small test case.
=> Detect @Delegate on record components

src/eclipseAgent/lombok/eclipse/agent/EclipsePatcher.java, src/eclipseAgent/lombok/launch/PatchFixesHider.java
- See https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3303 for API changes (I-build changes)
- Originally filed at https://github.com/redhat-developer/vscode-java/issues/4027
- Support older/newer API depending on the value of the first parameter
- TokenScanner#getTokenEndOffset(int, int) first parameter becomes an enum called TerminalToken
I've tested this PR with `test.eclipse-202503` & `test.eclipse-202503-full` and doesn't break anything there. The I-build tests appear broken even on the main branch, which makes sense (there's API breakage) so can't really test those, but I can confirm the PR resolves the stacktrace mentioned below.
With vscode-java (and even Lombok 1.18.38), create a simple project with a file that contains the `@Builder` annotation and import statement : …
=> Adapt to changes made in the JDT TokenScanner API.

.github/workflows/ant.yml, src/core/lombok/javac/JavacAST.java, src/delombok/lombok/delombok/PrettyPrinter.java, src/utils/lombok/javac/Javac.java
This PR adds support for JDK 25
I removed the mandatory warning because it is never used and it the `javac` method will be [gone soon too](https://github.com/openjdk/jdk/commit/cab515962b6940b50b975b12c8f5e99d0430f694#diff-7c7763cf662e3d88be93a2fd7557f1573cd793fd806e1ed3b86057456306e590).
=> Add support for JDK 25

src/delombok/lombok/delombok/DocCommentIntegrator.java, src/stubs/com/sun/tools/javac/parser/Tokens.java, src/utils/lombok/javac/Javac.java
This PR fixes #3940
The `stripIndent` method was added in JDK 25 and is required. I also adjusted our `validateJavadoc` method to trigger javadoc parsing.
=> Add missing stripIndent method

src/core/lombok/extern/jackson/Jacksonized.java, website/templates/features/experimental/Jacksonized.html
This is a follow-up PR for #3860, which was missing the documentation update for the website.
=> add website docs for Jacksonized Accessors
