projectlombok/lombok

- AUTHORS
- src/core/lombok/javac/handlers/JavacHandlerUtil.java
- src/delombok/lombok/delombok/FormatPreferences.java
Needs unit tests and ecj impl, but I thought I'd share my implementation of [issue 623](https://code.google.com/p/projectlombok/issues/detail?id=623) for javac.
> [i623] Added javac impl of javax.annotation.Generated

- src/core/lombok/Value.java
The usage example for @Value was erroneously using @Data.
> fixed example in @Value javadoc

- website/novideo.html
> Youtube video for "novideo"

- website/templates/setup/intellij.html
Only a little thing, but hopefully it all helps.
> Wrong IDE referenced in the restart step

- src/core/lombok/Builder.java
This fixes an outdated link in the Builder javadoc.
> Fix @Builder complete doc link.

- website/templates/setup/gradle.html
To fix https://github.com/rzwitserloot/lombok/issues/1425
> Updated setup instructions for Gradle

- usage_examples/experimental/WitherExample_post.jpage
- website/usageExamples/experimental/WitherExample_post.jpage
There was a small mistake in the WitherExample ordering of the construction parameters.
> fixing documentation mixup

- website/templates/features/experimental/FieldDefaults.html
Bug link: https://github.com/rzwitserloot/lombok/issues/1491
> #1491 Bugfix (Typo in FieldDefaults.html)

- src/core/lombok/javac/apt/LombokFileObjects.java
> Whitelist a JavacFileManager implementation

- website/templates/features/experimental/ExtensionMethod.html
> fixed ExtensionMethod example to return T (generic type)

- src/core/lombok/eclipse/handlers/HandleData.java
Relate to #1579: changes to improve memory usage
> #1579: recycle handlers to avoid excessive garbage collection

- docker/provision/jdk/java-10.sh
added java 10 download script (related to #1572)
> adding java10 download script

- src/core/lombok/javac/JavacAST.java
Fix issue #1632.
Some methods of AbstractLog seems to be removed in jdk11.
Fix JavacAST.Jdk9Plus to use new log methods added from jdk9.
> fix #1632: JavacAST: use new Log method for jdk11

- AUTHORS
- src/core/lombok/javac/apt/EmptyLombokFileObject.java
Signed-off-by: Victor Williams Stafusa da Silva <victorwssilva@gmail.com>
> Fix for #1617.

- build.xml
- src/core/lombok/core/AnnotationProcessor.java
- src/core/lombok/javac/apt/LombokProcessor.java
Fixes issue #1580
Any recommended way to set up test for this use case?
> Allow gradle incremental compiling with lombok

- AUTHORS
As requested, I added Pascal Bihler to author list and restored alphabetica…l order
> Missing Author addition

- doc/changelog.markdown
- src/launch/lombok/launch/ShadowClassLoader.java
Hi, could you add this in the master branch ? We definitly need to create custom annotations in a separated .jar.
> ShadowClassLoader is now friendlier to trying to extend lombok.

- website/templates/setup/gradle.html
otherwise gradle compile will fail.
> lombok config broken: version must be string

- src/core/lombok/core/handlers/HandlerUtil.java
Added Spring NonNull and Nullable annotations
> Added Spring NonNull and Nullable annotations

- src/core/lombok/eclipse/handlers/HandleBuilder.java
- src/core/lombok/javac/handlers/HandleBuilder.java
- src/core/lombok/javac/handlers/singulars/JavacGuavaSingularizer.java
- test/transform/resource/after-delombok/BuilderSingularWildcardListsWithToBuilder.java
- test/transform/resource/after-delombok/BuilderWithToBuilder.java
- test/transform/resource/after-ecj/BuilderSingularWildcardListsWithToBuilder.java
- test/transform/resource/after-ecj/BuilderWithToBuilder.java
- test/transform/resource/before/BuilderSingularWildcardListsWithToBuilder.java
Fixes #1885 by replacing the wildcard with the lower bound type.
Furthermore, this fixes missing type arguments when using `@ObtainVia` with a static method.
> toBuilder: wildcards and singular fix

- src/core/lombok/ConfigurationKeys.java
SuppressFBWArnings => SuppressFBWarnings
no-ars => no-args
> Fixed two minor typos

- src/core/lombok/core/handlers/HandlerUtil.java
This makes it easier to see what is there and to know where to add other annotations.
> Alphabetize list of annotations

- src/core/lombok/Builder.java
Fix doc for example about access level of Builder
> Fix Javadoc for @Builder

- src/core/lombok/core/handlers/HandlerUtil.java
> Fixed bug with 'lombok.experimental.flagUsage = ALLOW'

- website/templates/features/Value.html
To address https://github.com/rzwitserloot/lombok/issues/2056
> addition of documentation for using Value and NonFinal

- AUTHORS
> Add Till Brychcy to AUTHORS

- website/templates/features/experimental/Tolerate.html
- website/templates/features/experimental/index.html
- website/usageExamples/experimental/Tolerate_post.jpage
- website/usageExamples/experimental/Tolerate_pre.jpage
Update documentation with Tolerate. 
[#2249](https://github.com/rzwitserloot/lombok/issues/2249)
> Add documentation for Tolerate

- AUTHORS
- src/core/lombok/javac/handlers/HandleSuperBuilder.java
#2262 
Added ability to process JCField as a type parameter for HandleSuperBuilder. javac.
> Fixed @SuperBuilder with generic with inner static class produces CE

- src/core/lombok/core/configuration/NullAnnotationLibrary.java
> Make custom null annotation resolved in addNullAnnotations

- src/core/lombok/eclipse/handlers/HandleSuperBuilder.java
- test/transform/resource/after-delombok/SuperBuilderBasic.java
- test/transform/resource/after-ecj/SuperBuilderBasic.java
- test/transform/resource/before/SuperBuilderBasic.java
Well, I don't know how that ever worked...
> [SuperBuilder] fix IndexOutOfBounds (fixes #2407)

- src/core/lombok/core/handlers/HandlerUtil.java
Follow-up for PR #2387, as per remark of Jackson maintainer @cowtowncoder.
> [Jacksonized] copy JsonAutoDetect to builder class

- src/core/lombok/core/handlers/HandlerUtil.java
Follow-up for #2429, also see discussion in #2419.
> Also copy Jackson's JsonAlias and JsonView annotations to setter/builder

- src/core/lombok/core/handlers/HandlerUtil.java
> fix package name of JsonDeserialize

- AUTHORS
- src/core/lombok/javac/handlers/JavacHandlerUtil.java
- src/stubs/com/sun/tools/javac/code/Symbol.java
Fixes https://github.com/micronaut-projects/micronaut-core/issues/1566
> Fix missing parameter names, annotations in following annotation processors

- src/core/lombok/ConfigurationKeys.java
- src/core/lombok/eclipse/handlers/EclipseHandlerUtil.java
- src/core/lombok/eclipse/handlers/HandleGetter.java
- src/core/lombok/javac/handlers/HandleGetter.java
- src/core/lombok/javac/handlers/JavacHandlerUtil.java
- test/transform/resource/after-delombok/SkipSuppressWarnings.java
- test/transform/resource/after-ecj/SkipSuppressWarnings.java
- test/transform/resource/before/SkipSuppressWarnings.java
- test/transform/resource/messages-ecj/SkipSuppressWarnings.java.messages
- website/templates/features/configuration.html
> Add config key to turn off @SuppressWarnings("all")

- src/core/lombok/javac/handlers/HandleGetter.java
- test/transform/resource/after-delombok/GetterLazyArguments.java
- test/transform/resource/after-ecj/GetterLazyArguments.java
- test/transform/resource/before/GetterLazyArguments.java
This PR fixes #2300
I have noticed that, in addition to the reported case, there are more code snippets that fail (see test case).
> Keep method argument positions for lazy getter initializer

- src/core/lombok/eclipse/EclipseAST.java
- src/core/lombok/eclipse/TransformEclipseAST.java
This PR fixes #2489 and may also solve #1717 (at least to some extent, I identified this problem using the instructions mentioned there)
> Handle each Eclipse ASTs not more than two times (diet + full)

- src/eclipseAgent/lombok/eclipse/agent/PatchVal.java
This PR fixes #2566.
In `MessageSend.resolve` the constant field gets used as marker to run the first checks only once. Not resetting this value also skips the check for an empty `actualReceiverType` and leads to the reported NPE. While this one solves this problem we should consider to actual copy the initialization expression and run resolution on the copy. It looks like that this was the original idea some time ago but was never completed.
I also verified that this one still works in older eclipse versions.
> Reset constant value set during type resolution

- AUTHORS
- buildScripts/tests.ant.xml
- src/core/lombok/javac/handlers/JavacHandlerUtil.java
- src/delombok/lombok/delombok/PrettyPrinter.java
- test/configuration/src/lombok/core/configuration/TestConfiguration.java
This also should fix the #1745 issue.
The change of the TestConfiguration.java is based on the fact that
Git for Windows is configured with 'core.autocrlf=true' by default.
>  Fix tests under Windows, fix test.javac11 and test.javac14, fix issue #1745

- src/core/lombok/eclipse/handlers/EclipseHandlerUtil.java
- src/core/lombok/eclipse/handlers/HandleLog.java
- src/core/lombok/eclipse/handlers/HandleSuperBuilder.java
- src/eclipseAgent/lombok/eclipse/agent/EclipsePatcher.java
- src/eclipseAgent/lombok/launch/PatchFixesHider.java
Fix broken eclipse tests
Edit: It seems like `ant test` is broken too because it uses Java 8 code
> Eclipse test fixes

- src/core/lombok/core/AnnotationProcessor.java
- src/core/lombok/javac/apt/LombokProcessor.java
This PR fixes #2592. 
I also completed the potential fix for #2412 by @rspilker (he missed to add the additional field to `LombokProcessor`). I don't know why the code to search the processing environment is there at two places, thats why I have not moved it to a different class.
> Find ProcessingEnvironment in InteliJ 2020.3 and Kotlin

- doc/changelog.markdown
Just to conform with the rest of the references to Pull Requests in the changelog
> Add missing PR number

- website/templates/setup/intellij.html
Built in support is now available in IntelliJ
> Add information about 2020.3 having Lombok support

- src/core/lombok/javac/handlers/JavacHandlerUtil.java
- test/transform/resource/after-delombok/NullAnnotatedCheckerFrameworkSuperBuilder.java
- test/transform/resource/after-ecj/NullAnnotatedCheckerFrameworkSuperBuilder.java
- test/transform/resource/before/NullAnnotatedCheckerFrameworkSuperBuilder.java
> Do not lose generic arguments when adding annotations

- src/core/lombok/javac/handlers/JavacSingularsRecipes.java
> Create void literal properly

- src/core/lombok/eclipse/handlers/HandleSuperBuilder.java
- test/transform/resource/after-delombok/SuperBuilderInitializer.java
- test/transform/resource/after-ecj/SuperBuilderInitializer.java
- test/transform/resource/before/SuperBuilderInitializer.java
> SuperBuilder now skips initializers while gathering types

- src/delombok/lombok/delombok/Delombok.java
- src/delombok/lombok/delombok/DelombokApp.java
- src/delombok/lombok/delombok/ant/DelombokTaskImpl.java
- test/core/src/lombok/RunTestsViaDelombok.java
Fixes awhitford/lombok.maven#47
> [jdk16] Add lombok opens in single location

- src/eclipseAgent/lombok/eclipse/agent/EclipseLoaderPatcherTransplants.java
This PR fixes #2810 
Since Java 16 reflective access to `ClassLoader.defineClass` is no longer permitted. The recommended solution is to use `MethodHandles.lookup().defineClass` which is useless here because it is limited to classes in the same package. Fortunately the relvant code gets transplanted into a `ClassLoader` and we can call the parent method using a `MethodHandle`.
> Use MethodHandler instead of reflective defineClass

- src/core/lombok/eclipse/handlers/HandleLog.java
- src/core/lombok/javac/handlers/HandleLog.java
Should resolve the issue #2821
> Fix @CustomLog-key in lombok.config for some error messages. Issue #2821

- src/core/lombok/eclipse/handlers/EclipseHandlerUtil.java
- src/core/lombok/javac/handlers/JavacHandlerUtil.java
- test/transform/resource/after-delombok/OnXJava7Style.java
- test/transform/resource/after-delombok/OnXJava8Style.java
- test/transform/resource/after-ecj/OnXJava7Style.java
- test/transform/resource/after-ecj/OnXJava7StyleOn8.java
- test/transform/resource/after-ecj/OnXJava8Style.java
- test/transform/resource/after-ecj/OnXJava8StyleOn7.java
- test/transform/resource/before/OnXJava7Style.java
- test/transform/resource/before/OnXJava7StyleOn8.java
- test/transform/resource/before/OnXJava8Style.java
- test/transform/resource/before/OnXJava8StyleOn7.java
This PR fixes #3040
There also was an ecj issue that I found by adding the test cases.
> Support array initializer in onX

- src/core/lombok/core/configuration/ConfigurationFile.java
Hi
I have removed a typo error of 2 semicolons at the end of two lines
ciao
matteo
> Removed double semicolon

- buildScripts/ivy.xml
- test/transform/resource/messages-delombok/LoggerSlf4jOnNonType.java.messages
This PR requires a new lombok.patcher release (0.44) (https://github.com/projectlombok/lombok.patcher/pull/9)
Issue: #3129
> Add support for JDK 18

- src/core/lombok/eclipse/handlers/EclipseHandlerUtil.java
- src/core/lombok/eclipse/handlers/EclipseSingularsRecipes.java
- src/core/lombok/eclipse/handlers/HandleEqualsAndHashCode.java
- src/core/lombok/eclipse/handlers/HandleWithBy.java
- src/core/lombok/eclipse/handlers/singulars/EclipseGuavaSingularizer.java
- src/core/lombok/eclipse/handlers/singulars/EclipseJavaUtilListSetSingularizer.java
- src/core/lombok/eclipse/handlers/singulars/EclipseJavaUtilMapSingularizer.java
Ensure that bit for HasTypeAnnotations is set correctly whenever generating a known nullability type annotation.
> [fixes #3133] Additional bits setting when creating type annotations

- src/core/lombok/javac/handlers/HandleExtensionMethod.java
- test/transform/resource/after-delombok/ExtensionMethodNonStatic.java
- test/transform/resource/after-ecj/ExtensionMethodNonStatic.java
- test/transform/resource/before/ExtensionMethodNonStatic.java
> Ignore non-static/non-public extension methods

- src/core/lombok/javac/JavacAST.java
- src/core/lombok/javac/handlers/HandleVal.java
- src/core/lombok/javac/handlers/JavacHandlerUtil.java
- src/delombok/lombok/delombok/PrettyPrinter.java
- test/pretty/resource/after/RecordPattern19.java
- test/pretty/resource/after/RecordPattern20.java
- test/pretty/resource/before/RecordPattern19.java
- test/pretty/resource/before/RecordPattern20.java
> Add support for JDK 20

- AUTHORS
As discussed with @rzwitserloot
> Add author

- src/core/lombok/eclipse/handlers/HandleNonNull.java
- src/core/lombok/javac/handlers/HandleNonNull.java
- test/transform/resource/after-delombok/NonNullOnRecordExistingConstructor.java
- test/transform/resource/after-delombok/NonNullOnRecordExistingSetter.java
- test/transform/resource/after-delombok/NonNullOnRecordSimple.java
- test/transform/resource/after-delombok/NonNullOnRecordTypeUse.java
- test/transform/resource/after-ecj/NonNullOnRecordExistingConstructor.java
- test/transform/resource/after-ecj/NonNullOnRecordExistingSetter.java
- test/transform/resource/after-ecj/NonNullOnRecordSimple.java
- test/transform/resource/after-ecj/NonNullOnRecordTypeUse.java
- test/transform/resource/before/NonNullOnRecord.java
- test/transform/resource/before/NonNullOnRecord2.java
- test/transform/resource/before/NonNullOnRecordExistingConstructor.java
- test/transform/resource/before/NonNullOnRecordExistingSetter.java
- test/transform/resource/before/NonNullOnRecordSimple.java
- test/transform/resource/before/NonNullOnRecordTypeUse.java
This PR fixes #3366
I also renamed the existing tests, adding `NonNullOnRecord4` felt wrong :smile:
> Handle @NonNull type annotations on record components

- src/eclipseAgent/lombok/launch/PatchFixesHider.java
> Find jdt.core classloader if initialized in batch mode

- src/core/lombok/javac/JavacImportList.java
- src/core/lombok/javac/handlers/JavacHandlerUtil.java
- src/delombok/lombok/delombok/Delombok.java
- src/delombok/lombok/delombok/PrettyPrinter.java
- src/utils/lombok/javac/Javac.java
- src/utils/lombok/javac/JavacTreeMaker.java
- test/pretty/resource/after/RecordPattern21.java
- test/pretty/resource/after/Switch21.java
- test/pretty/resource/before/RecordPattern20.java
- test/pretty/resource/before/RecordPattern21.java
- test/pretty/resource/before/Switch21.java
This PR adds support for JDK21. There are some failing unrelated tests that were fixed in https://github.com/projectlombok/lombok/commit/1599bc1ce4a2440322af7a1183828c5f65dcc237.
Fixes #3393
> Add support for JDK21

- src/core/lombok/eclipse/handlers/EclipseHandlerUtil.java
- test/transform/resource/after-delombok/JacksonizedOnRecord.java
- test/transform/resource/after-ecj/JacksonizedOnRecord.java
- test/transform/resource/before/JacksonizedOnRecord.java
This PR fixes #3315
There are some failing unrelated tests that were fixed in https://github.com/projectlombok/lombok/commit/1599bc1ce4a2440322af7a1183828c5f65dcc237.
> Copy annotations on record components

- src/core/lombok/javac/handlers/HandleExtensionMethod.java
- test/transform/resource/after-delombok/ExtensionMethodInLambda.java
- test/transform/resource/after-ecj/ExtensionMethodInLambda.java
- test/transform/resource/before/ExtensionMethodInLambda.java
- test/transform/resource/messages-delombok/ExtensionMethodInLambda.java.messages
- test/transform/resource/messages-ecj/ExtensionMethodInLambda.java.messages
- test/transform/resource/messages-idempotent/ExtensionMethodInLambda.java.messages
> Delay replacement of extension methods in arguments

- src/core/lombok/javac/handlers/HandleExtensionMethod.java
- src/core/lombok/javac/handlers/JavacHandlerUtil.java
- test/transform/resource/after-delombok/ExtensionMethodOnRecord.java
- test/transform/resource/after-ecj/ExtensionMethodOnRecord.java
- test/transform/resource/before/ExtensionMethodOnRecord.java
This PR fixes #3450
No real changes, I only adjusted the check for javac and added a test case.
> Add support for extension methods on records

- src/core/lombok/eclipse/handlers/EclipseHandlerUtil.java
- src/core/lombok/eclipse/handlers/HandleBuilder.java
- src/core/lombok/eclipse/handlers/HandleSuperBuilder.java
- src/core/lombok/javac/handlers/HandleBuilder.java
- src/core/lombok/javac/handlers/HandleSuperBuilder.java
- src/core/lombok/javac/handlers/JavacHandlerUtil.java
- test/transform/resource/after-delombok/SuperBuilderJavadoc.java
- test/transform/resource/after-ecj/SuperBuilderJavadoc.java
- test/transform/resource/before/SuperBuilderJavadoc.java
> Copy javadoc to generated SuperBuilder

- buildScripts/ivy.xml
- src/eclipseAgent/lombok/eclipse/agent/PatchExtensionMethod.java
- test/transform/resource/after-delombok/ExtensionMethodAmbiguousFunctional.java
- test/transform/resource/after-ecj/ExtensionMethodAmbiguousFunctional.java
- test/transform/resource/before/ExtensionMethodAmbiguousFunctional.java
- test/transform/resource/messages-delombok/ExtensionMethodAmbiguousFunctional.java.messages
- test/transform/resource/messages-ecj/ExtensionMethodAmbiguousFunctional.java.messages
> Handle ambiguous extension methods

- src/core/lombok/eclipse/handlers/HandleGetter.java
- src/core/lombok/javac/handlers/HandleGetter.java
- test/transform/resource/after-delombok/DelegateOnGetter.java
- test/transform/resource/after-delombok/GetterLazy.java
- test/transform/resource/after-delombok/GetterLazyArguments.java
- test/transform/resource/after-delombok/GetterLazyBoolean.java
- test/transform/resource/after-delombok/GetterLazyEahcToString.java
- test/transform/resource/after-delombok/GetterLazyErrorPosition.java
- test/transform/resource/after-delombok/GetterLazyGenerics.java
- test/transform/resource/after-delombok/GetterLazyInAnonymousClass.java
- test/transform/resource/after-delombok/GetterLazyNative.java
- test/transform/resource/after-delombok/GetterLazyTransient.java
- test/transform/resource/after-delombok/SkipSuppressWarnings.java
- test/transform/resource/after-ecj/DelegateOnGetter.java
- test/transform/resource/after-ecj/GetterLazy.java
- test/transform/resource/after-ecj/GetterLazyArguments.java
- test/transform/resource/after-ecj/GetterLazyBoolean.java
- test/transform/resource/after-ecj/GetterLazyEahcToString.java
- test/transform/resource/after-ecj/GetterLazyGenerics.java
- test/transform/resource/after-ecj/GetterLazyInAnonymousClass.java
- test/transform/resource/after-ecj/GetterLazyNative.java
- test/transform/resource/after-ecj/GetterLazyTransient.java
- test/transform/resource/after-ecj/SkipSuppressWarnings.java
> Use $value instead of value in lazy getter

- .github/workflows/ant.yml
- buildScripts/ivy.xml
- buildScripts/setup.ant.xml
- buildScripts/tests.ant.xml
- docker/provision/jdk/java-22.sh
- src/core/lombok/eclipse/handlers/EclipseHandlerUtil.java
- src/eclipseAgent/lombok/eclipse/agent/EclipsePatcher.java
- src/eclipseAgent/lombok/eclipse/agent/PatchDelegate.java
- src/eclipseAgent/lombok/eclipse/agent/PatchJavadoc.java
- src/eclipseAgent/lombok/launch/PatchFixesHider.java
- test/eclipse/resource/delegate/model/DelegateModel.java
- test/eclipse/resource/javadoc/getterSetter/Javadoc.java
- test/eclipse/src/lombok/eclipse/EclipseTests.java
- test/eclipse/src/lombok/eclipse/misc/DelegateTest.java
- test/eclipse/src/lombok/eclipse/misc/JavadocTest.java
This PR fixes #3620
I couldn't find a better solution to fix the delegate stuff in Eclipse. The changed method signature is really hard to handle. I hope the reflection stuff doesn't affect performance too much...
> Add support for Eclipse 2024-03 (4.31)

- website/templates/features/With.html
Remove stray **<>** from https://projectlombok.org/features/With
> Fix typo in With.html

- .github/workflows/ant.yml
- src/core/lombok/javac/handlers/JavacHandlerUtil.java
- src/utils/lombok/javac/Javac.java
- src/utils/lombok/javac/TreeMirrorMaker.java
This PR fixes #3772, fixes #3814
> Add JDK 24 support

- src/stubs/com/sun/tools/javac/parser/Tokens.java
- src/utils/lombok/javac/Javac.java
> Fix RuntimeException in Javac$JavadocOps

- src/core/lombok/javac/handlers/HandleEqualsAndHashCode.java
- src/core/lombok/javac/handlers/HandleLog.java
- src/core/lombok/javac/handlers/HandleNonNull.java
- src/core/lombok/javac/handlers/JavacHandlerUtil.java
- test/core/src/lombok/RunTestsViaDelombok.java
> Create copies for expressions

- .github/workflows/ant.yml
Github Actions workflow appears to be failing because of invalid YAML configuration and indentation issues. This PR should fix that.
> Fix github workflow YAML configuration
